[package]
name = "vit-servicing-station-server"
version = "0.3.4-dev"
authors = ["danielsanchezq <daniel.sanchez@iohk.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.11"
opentelemetry.workspace = true
opentelemetry-otlp.workspace = true
opentelemetry-semantic-conventions.workspace = true
clap = { workspace = true }
thiserror = "1.0.37"
tokio = { version = "^1.0", features = ["macros", "rt-multi-thread"] }
tracing.workspace = true
tracing-futures.workspace = true
tracing-subscriber = { workspace = true, features=["fmt"] }
tracing-appender.workspace = true
tracing-opentelemetry.workspace = true
url = "2"
vit-servicing-station-lib = { path = "../vit-servicing-station-lib" }
