[package]
name = "jormungandr"
version = "0.13.0"
authors = [ "dev@iohk.io" ]
license = "MIT OR Apache-2.0"
repository = "https://github.com/input-output-hk/jormungandr"
homepage = "https://github.com/input-output-hk/jormungandr#README.md"
documentation = "https://github.com/input-output-hk/jormungandr#USAGE.md"
description = """
Midgard Serpent
"""
edition = "2021"

[dependencies]
chain-addr = { path = "../../chain-libs/chain-addr" }
chain-core = { path = "../../chain-libs/chain-core" }
chain-crypto = { path = "../../chain-libs/chain-crypto" }
chain-impl-mockchain = { path = "../../chain-libs/chain-impl-mockchain" }
chain-network = { path = "../../chain-libs/chain-network" }
chain-storage   = { path = "../../chain-libs/chain-storage" }
chain-time      = { path = "../../chain-libs/chain-time" }
chain-vote = { path = "../../chain-libs/chain-vote" }
chain-evm = { path = "../../chain-libs/chain-evm", optional = true }
cardano-legacy-address = { path = "../../chain-libs/cardano-legacy-address" }
imhamt = { path = "../../chain-libs/imhamt" }

arc-swap = "^1.5.0"
async-trait = "0.1.51"
base64 = "0.13.0"
bech32 = "0.8"
futures = "0.3.21"
hex = "0.4"
jormungandr-lib = { path = "../jormungandr-lib" }
keynesis = "1.1"
lazy_static = "1.4"
linked-hash-map = "0.5"
opentelemetry = { version = "0.18", features = ["rt-tokio"] }
opentelemetry-otlp = "0.11.0"
opentelemetry-semantic-conventions = "0.10.0"
poldercast = "1.2"
multiaddr = { package = "parity-multiaddr", version = "0.11" }
rand = "0.8"
rand_chacha = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0.81"
serde_yaml = "0.8"
structopt = "^0.3"
time = { version = "0.3", features = ["macros"] }
thiserror = "1.0.30"
tracing = "0.1"
tracing-futures = "0.2"
tracing-gelf = { version = "0.6", optional = true }
# TODO unpin this when cross for ARM targets is fixed: https://github.com/cross-rs/cross/pull/591
tracing-journald = { version = "=0.2.0", optional = true }
tracing-opentelemetry = "0.18.0"
tracing-subscriber = { version = "0.3", features = ["fmt", "json", "time"] }
tracing-appender = "0.2"
tokio = { version = "^1.15", features = ["rt-multi-thread", "time", "sync", "rt", "signal", "test-util"] }
tokio-stream = { version = "0.1.4", features = ["sync"] }
tokio-util = { version = "0.6.0", features = ["time"] }
tonic = "0.6"
url = { version = "2", features = ["serde"] }
lru = "0.7"
warp = { version = "0.3.2", features = ["tls"] }
serde_with = { version = "2", features = ["macros"] }
http-zipkin = "0.3.0"
prometheus = { version = "0.13", optional = true }
jsonrpsee-http-server = { version = "0.11.0" }
jsonrpsee-core = { version = "0.11.0" }
reqwest = { version = "0.11",  default-features = false, features = ["rustls-tls"] }
local-ip-address = "0.4.9"

[dev-dependencies]
tokio = { version = "^1.15", features = ["full"] }
quickcheck = "0.9"
quickcheck_macros = "0.9"
chain-impl-mockchain = { path = "../../chain-libs/chain-impl-mockchain", features = [ "property-test-api" ] }
chain-addr = { path = "../../chain-libs/chain-addr", features = [ "property-test-api" ] }
chain-crypto = { path = "../../chain-libs/chain-crypto", features = [ "property-test-api" ] }
criterion = { version = "0.3", features = ["html_reports", "async_tokio"] }

[[bench]]
name = "rest_v0"
harness = false


[build-dependencies]
versionisator = "1.0.2"

[target.'cfg(unix)'.dependencies]
libc = "0.2.124"
nix = "0.25"

[features]
default = ["codegen-rustfmt"]
with-bench = []
codegen-rustfmt = ["chain-network/codegen-rustfmt"]
integration-test = []
soak-test = []
systemd = ["tracing-journald"]
gelf = ["tracing-gelf"]
prometheus-metrics = ["prometheus"]
evm = [ "chain-impl-mockchain/evm", "jormungandr-lib/evm", "chain-evm" ]
