VERSION 0.6
FROM debian:bullseye-slim

WORKDIR /app

build:
    FROM ../../../+build-workspace
    RUN cargo build --locked --release --bin jormungandr
    SAVE ARTIFACT target/release/jormungandr jormungandr

docker:
    ARG tag="latest"

    COPY +build/jormungandr .
    ENTRYPOINT ["/app/jormungandr"]
    SAVE IMAGE jormungandr:$tag
