VERSION 0.7

build:
    FROM ../../../+build-workspace
    RUN with_nix cargo build --locked --release --bin jormungandr
    SAVE ARTIFACT target/release/jormungandr jormungandr

docker:
    FROM debian:stable-slim
    ARG tag="latest"
    ARG registry

    COPY +build/jormungandr .
    ENTRYPOINT ["/app/jormungandr"]
    SAVE IMAGE ${registry}jormungandr:$tag
