/*
 * Catalyst 1.0
 *
 * Revised API expressing all capabilities of the Catalyst 1.0 Backend.  TODO: * Implement Permissionless Auth. * Implement Replacement Functionality for GVC. * Implement drep registration on main-chain, distinct from voter registration. * Implement Voting API abstracting the Jormungandr API from public exposure. * Implement Audit API's (Retrieve voting blockchain records,  registration/voting power audit and private tally audit. * Implement API's needed to support posting Ideas/Proposals etc.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: steven.johnson@iohk.io
 * Generated by: https://openapi-generator.tech
 */

/// AdvisorReview : Review of a Proposal by a Community Advisor

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AdvisorReview {
    /// Anonymized Assessor identity. All reviews by the same Assessor will have the same identity string.
    #[serde(
        rename = "assessor",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub assessor: Option<Option<serde_json::Value>>,
    /// List of review ratings given by this reviewer.
    #[serde(
        rename = "ratings",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub ratings: Option<Option<serde_json::Value>>,
}

impl AdvisorReview {
    /// Review of a Proposal by a Community Advisor
    pub fn new() -> AdvisorReview {
        AdvisorReview {
            assessor: None,
            ratings: None,
        }
    }
}
