/*
 * Catalyst 1.0
 *
 * Revised API expressing all capabilities of the Catalyst 1.0 Backend.  TODO: * Implement Permissionless Auth. * Implement Replacement Functionality for GVC. * Implement drep registration on main-chain, distinct from voter registration. * Implement Voting API abstracting the Jormungandr API from public exposure. * Implement Audit API's (Retrieve voting blockchain records,  registration/voting power audit and private tally audit. * Implement API's needed to support posting Ideas/Proposals etc.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: steven.johnson@iohk.io
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DelegatorInfo {
    /// List off delegations made by this stake address. In the order as presented in the voters registration.
    #[serde(
        rename = "delegations",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub delegations: Option<Option<serde_json::Value>>,
    /// Hex encoded reward address for this delegation.
    #[serde(
        rename = "reward_address",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub reward_address: Option<Option<serde_json::Value>>,
    /// Raw total voting power from stake address
    #[serde(
        rename = "raw_power",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub raw_power: Option<Option<serde_json::Value>>,
    /// Total voting power, across all registered voters.
    #[serde(
        rename = "total_power",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub total_power: Option<Option<serde_json::Value>>,
    /// Date and time for the latest update to this snapshot information.
    #[serde(
        rename = "last_updated",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub last_updated: Option<Option<serde_json::Value>>,
    /// Date and time the latest snapshot represents.
    #[serde(
        rename = "as_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub as_at: Option<Option<serde_json::Value>>,
    /// `True` = this is the final snapshot which will be used for voting power in the event.</br>`False` =This is an interim snapshot, subject to change.
    #[serde(
        rename = "final",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub r#final: Option<Option<serde_json::Value>>,
}

impl DelegatorInfo {
    pub fn new() -> DelegatorInfo {
        DelegatorInfo {
            delegations: None,
            reward_address: None,
            raw_power: None,
            total_power: None,
            last_updated: None,
            as_at: None,
            r#final: None,
        }
    }
}
