/*
 * Catalyst 1.0
 *
 * Revised API expressing all capabilities of the Catalyst 1.0 Backend.  TODO: * Implement Permissionless Auth. * Implement Replacement Functionality for GVC. * Implement drep registration on main-chain, distinct from voter registration. * Implement Voting API abstracting the Jormungandr API from public exposure. * Implement Audit API's (Retrieve voting blockchain records,  registration/voting power audit and private tally audit. * Implement API's needed to support posting Ideas/Proposals etc.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: steven.johnson@iohk.io
 * Generated by: https://openapi-generator.tech
 */

/// ProposerDetails : Details about a proposer for a particular proposal.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProposerDetails {
    /// Name of the author/s of the proposal.
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<serde_json::Value>>,
    /// Email contact address of the author/s of the proposal. If not present, there is no known contact email for the authors.
    #[serde(rename = "email", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub email: Option<Option<serde_json::Value>>,
    /// URL to a web resource with details about the author/s of the proposal.
    #[serde(rename = "url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub url: Option<Option<serde_json::Value>>,
    /// The Payment Address the Funds requested will be paid to. Will not be included if the proposal does not request funds.
    #[serde(rename = "payment_key", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub payment_key: Option<Option<serde_json::Value>>,
}

impl ProposerDetails {
    /// Details about a proposer for a particular proposal.
    pub fn new() -> ProposerDetails {
        ProposerDetails {
            name: None,
            email: None,
            url: None,
            payment_key: None,
        }
    }
}


