/*
 * Catalyst 1.0
 *
 * Revised API expressing all capabilities of the Catalyst 1.0 Backend.  TODO: * Implement Permissionless Auth. * Implement Replacement Functionality for GVC. * Implement drep registration on main-chain, distinct from voter registration. * Implement Voting API abstracting the Jormungandr API from public exposure. * Implement Audit API's (Retrieve voting blockchain records,  registration/voting power audit and private tally audit. * Implement API's needed to support posting Ideas/Proposals etc.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: steven.johnson@iohk.io
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VoterGroup {
    #[serde(rename = "group", skip_serializing_if = "Option::is_none")]
    pub group: Option<crate::models::VoterGroupId>,
    /// The identifier of voting power token used withing this group. All vote plans within a group are guaranteed to use the same token.
    #[serde(
        rename = "voting_token",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub voting_token: Option<Option<serde_json::Value>>,
}

impl VoterGroup {
    pub fn new() -> VoterGroup {
        VoterGroup {
            group: None,
            voting_token: None,
        }
    }
}
