/*
 * Catalyst 1.0
 *
 * Revised API expressing all capabilities of the Catalyst 1.0 Backend.  TODO: * Implement Permissionless Auth. * Implement Replacement Functionality for GVC. * Implement drep registration on main-chain, distinct from voter registration. * Implement Voting API abstracting the Jormungandr API from public exposure. * Implement Audit API's (Retrieve voting blockchain records,  registration/voting power audit and private tally audit. * Implement API's needed to support posting Ideas/Proposals etc.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: steven.johnson@iohk.io
 * Generated by: https://openapi-generator.tech
 */

/// VoterGroupId : Voters Group ID.</br>`direct` = Direct voter.</br>`rep` = Delegated Representative.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VoterGroupId {
}

impl VoterGroupId {
    /// Voters Group ID.</br>`direct` = Direct voter.</br>`rep` = Delegated Representative.
    pub fn new() -> VoterGroupId {
        VoterGroupId {
        }
    }
}


