[package]
name = "jormungandr-lib"
version = "0.13.0"
authors = ["dev@iohk.io"]
edition = "2021"

description = "Data structures and formats used by Jormungandr node API and configuration files"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_with = { version = "2", features = ["macros"] }
chain-impl-mockchain = { workspace = true }
chain-addr      = { path = "../../chain-libs/chain-addr" }
chain-core      = { path = "../../chain-libs/chain-core" }
chain-crypto    = { path = "../../chain-libs/chain-crypto" }
chain-time      = { path = "../../chain-libs/chain-time"}
chain-vote      = { path = "../../chain-libs/chain-vote" }
cardano-legacy-address = { path = "../../chain-libs/cardano-legacy-address" }
typed-bytes = { path = "../../chain-libs/typed-bytes" }
rand = "0.8"
rand_core = "0.6"
rand_chacha = "0.3"
time = { version = "0.3", features = ["serde", "local-offset", "parsing", "formatting", "macros"]}
humantime = "2.0"
thiserror = "1.0"
multiaddr = { package = "parity-multiaddr", version = "0.11", default-features = false }
hex = "0.4"
bech32 = "0.8"
base64 = "0.13.0"
http = "0.2.2"

[dev-dependencies]
bincode = "1.3.3"
quickcheck = "0.9"
quickcheck_macros = "0.9"
# FIXME required to work with quickcheck 0.9. Remove after migrating another crate or newer quickcheck
rand07 = { package = "rand", version = "0.7" }
chain-impl-mockchain = { workspace = true, features = [ "property-test-api" ] }
chain-addr      = { path = "../../chain-libs/chain-addr", features = [ "property-test-api" ] }
chain-crypto    = { path = "../../chain-libs/chain-crypto", features = [ "property-test-api" ] }
ed25519-bip32 = "0.4.1"
serde_yaml = "0.8"
serde_json = "1.0"
