rest:
  listen: "127.0.0.1:8081"

skip_bootstrap: true

p2p:
  bootstrap:
    node_key_file: null
    trusted_peers: null
    max_bootstrap_attempts: null
  connection:
    public_address: "/ip4/127.0.0.1/tcp/9081"
