# Build scripts for Catalyst-Core
# This file is built with `cargo make` see:
#  <https://github.com/sagiegurari/cargo-make>
extend = [
    { path = "Makefiles/prereqs.toml"  },
    { path = "Makefiles/docs.toml"  },
    { path = "Makefiles/db.toml"  },
    { path = "Makefiles/docker.toml"  }
]

env_files = [
    { path = ".config/rustdoc.env", defaults_only = true },
]

[config]
min_version = "0.36.3"

# env vars common to all profiles
[env]

# env vars specific to a development build profile
[env.development]

# env vars specific to a production build profile
[env.production]

