--sql
-- Data from Catalyst Fund 2 - First Funded Event
-- AUTOGENERATED - DO NOT EDIT

-- Purge all Fund 2 data before re-inserting it.
DELETE FROM event WHERE row_id = 2;

-- Load the raw Block0 Binary from the file.
\set block0path 'historic_data/fund_2/block0.bin'
\set block0contents `base64 :block0path`

-- Create the Event record for Fund 2

INSERT INTO event
(row_id, name, description,
 start_time,
 end_time,
 registration_snapshot_time,
 snapshot_start,
 voting_power_threshold,
 max_voting_power_pct,
 insight_sharing_start,
 proposal_submission_start,
 refine_proposals_start,
 finalize_proposals_start,
 proposal_assessment_start,
 assessment_qa_start,
 voting_start,
 voting_end,
 tallying_end,
 block0,
 block0_hash,
 committee_size,
 committee_threshold)
VALUES

(2, 'Catalyst Fund 2', 'How will we encourage developers and entrepreneurs to build Dapps and businesses on top of Cardano in the next 6 months?',
 '2020-09-23 00:00:00', -- Start Time - Date accurate, time not known.
 '2021-01-10 20:00:00', -- End Time   - Date/Time accurate.
 '2020-12-15 17:00:04', -- Registration Snapshot Time - Date/time Accurate. Slot 16485313
                        -- DB Says 2020-12-15T17:00:00Z -- Inaccurate
 '2020-12-15 17:30:00', -- Snapshot Start - Date/time Accurate. Slot?
 7950000000,            -- Voting Power Threshold -- Accurate
 100,                   -- Max Voting Power PCT - No max% threshold used in this fund.
 NULL,                  -- Insight Sharing Start - None
 '2020-09-23 00:00:00', -- Proposal Submission Start - Date accurate, time not known.
 NULL,                  -- Refine Proposals Start - Date accurate, time not known.
 '2020-10-21 23:59:59', -- Finalize Proposals Start - Date accurate, time not known.
 NULL,                  -- Proposal Assessment Start - None
 NULL,                  -- Assessment QA Start - None
 '2020-12-15 21:00:00', -- Voting Starts - Date/time Accurate.
 '2021-01-04 20:00:00', -- Voting Ends - Date/time Accurate.
 '2021-01-10 20:00:00', -- Tallying Ends - Date/time Accurate.
 decode(:'block0contents','base64'),
                        -- Block 0 Data - From File
 NULL,                  -- Block 0 Hash - TODO
 0,                     -- Committee Size - No Encrypted Votes
 0                      -- Committee Threshold - No Encrypted Votes
 );

-- Free large binary file contents
\unset block0contents

--sql
-- Only 1 Challenge for FUND 2
INSERT INTO objective
(
    id,
    event,
    category,
    title,
    description,
    rewards_currency,
    rewards_total,
    rewards_total_lovelace,
    proposers_rewards,
    vote_options
)
VALUES
(
    0, -- Ideascale ID not known.
    2, -- Event 2
    'catalyst-simple', -- Category
    'Fund 2 Challenge', -- Title
    '', -- No Description
    'USD_ADA', -- Currency
    250000, -- USD
    2336450000000, -- Lovelace
    NULL, -- Don't know
    1
);

--sql
-- All Proposals for  FUND 2
INSERT INTO proposal
(
    id,
    objective,
    title,
    summary,
    category,
    public_key,
    funds,
    url,
    files_url,
    impact_score,
    extra,
    proposer_name,
    proposer_contact,
    proposer_url,
    proposer_relevant_experience,
    bb_proposal_id,
    bb_vote_options
)
VALUES
--sql
(
    324335,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Weblinks to Stakepools & Portfolios',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '60000000000', -- funds
    'http://ideascale.com/t/UM5UZBbJ8', -- url
    '', -- files_url
    314, -- impact_score
    '{"problem": "The Cardano ecosystem has no way to generate or send links pointing directly to stake pools or pool lists, either for sharing or delegation.", "solution": "Link pool names & weighted lists of stake pools (portfolios) into Cardano wallets & delegation tools from anywhere on the Internet"}', -- extra
    'rphair', -- proposer name
    'rphair@cosd.com', -- proposer contact
    'https://github.com/rphair/CIPs/blob/uri-delegation-portfolio/CIP-COSD-MultiPoolStakeURIscheme/CIP-COSD-MultiPoolStakeURIscheme.md', -- proposer URL
    'https://cosd.com/rphair-cv.html

Systems integration, networking, UI/UX design, technical writing & project management spanning 30 years.', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    324317,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'IoT Utility Dapp - Sign Tx Arduino',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '75000000000', -- funds
    'http://ideascale.com/t/UM5UZBbJq', -- url
    '', -- files_url
    396, -- impact_score
    '{"problem": "There is no simple method to sign embedded Cardano transactions in C. We can engage developers by building an Arduino compatible library", "solution": "Create an Arduino IDE compatible C library to sign local Cardano transactions - enable immediate applications for embedded & IoT pre-Goguen"}', -- extra
    'Kyle Solomon [FROG]', -- proposer name
    'ksolomon@adosia.com', -- proposer contact
    'https://adosia.com', -- proposer URL
    'BSE EE, 5 yrs semiconductor sales, built/pivoted ad-tech startup into open hw IoT init, ICO vet, SPO

https://www.linkedin.com/in/kesolomon/', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    324315,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Streamlining Cardano Communication',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '10000000000', -- funds
    'http://ideascale.com/t/UM5UZBbJo', -- url
    '', -- files_url
    121, -- impact_score
    '{"problem": "Currently cardano community provides an enormous amount of content in relation to cardano. We have multiple Outlets of information", "solution": "I I proposed creating a central location of information. Within all cardano wallet platforms using a off-chain data aggregation server"}', -- extra
    'Razorblock52', -- proposer name
    'Razorblock52@gmail.com', -- proposer contact
    '', -- proposer URL
    'I would hire a company to execute the cardano connection smash server. Using a developer or a company to build the platform.', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    324303,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Understand developers'' feelings',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '12500000000', -- funds
    'http://ideascale.com/t/UM5UZBbJc', -- url
    '', -- files_url
    393, -- impact_score
    '{"problem": "Most entrepreneurs/devs wanting to use the blockchain are already doing it, and they will not migrate unless they have the right incentives.", "solution": "Assess potential incentives for entrepreneurs/devs to migrate by understanding what they love and hate about their current chain."}', -- extra
    'Borja Bonet Segui', -- proposer name
    'borja.bonet.segui@gmail.com', -- proposer contact
    'https://www.linkedin.com/in/borja-bonet-segui/', -- proposer URL
    'MBA Thesis involving research, interviews and surveys.

Worked in market research

Pilot project interviewing startups: ambitioustracks.com', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    324242,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'ERC-* smart contracts conventer',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '260000000000', -- funds
    'http://ideascale.com/t/UM5UZBbIc', -- url
    '', -- files_url
    298, -- impact_score
    '{"problem": "Together with Tatum we want to build a standardized converter from Ethereum-based ERC-\\* smart contracts to the Cardano-based smart contracts", "solution": "Presently, there is no tool in the Cardano ecosystem, which will enable a smooth and fast transition from EVM based blockchains and SC."}', -- extra
    'Lukas Barta (Cardanians.io)', -- proposer name
    'lukas@cardanians.io', -- proposer contact
    'https://github.com/tatumio/', -- proposer URL
    'Tatum helps developers build blockchain apps without any previous knowledge of the blockchain.', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    324221,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Encouraging Wider ADA Distribution',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '350000000000', -- funds
    'http://ideascale.com/t/UM5UZBbIG', -- url
    '', -- files_url
    258, -- impact_score
    '{"problem": "Organizations that offer incentives boost productivity ++by at least 45%++. Distributed teams are disadvantaged due to localization challenges.", "solution": "Teams use our cross-chain interface to buy/deposit, manage, and share crypto assets across internal sub-wallets assigned to team members."}', -- extra
    'Justin Ahn', -- proposer name
    'justin@quid.li', -- proposer contact
    'https://quid.li', -- proposer URL
    'V.1 with btc launched, April

V.2 with Ethereum smart contracts, eth & dai support added, June, July

Onboarded >100 wallets, 43 are active', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    324179,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Solar Power Plants development',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '2500000000000', -- funds
    'http://ideascale.com/t/UM5UZBbHa', -- url
    '', -- files_url
    136, -- impact_score
    '{"problem": "We''re still using fossil fuels and not solar power.", "solution": "We want to begin utilizing Solar Power Plants, such as Tesla Megapack to introduce solar power to grid infrastructures, starting in Belize."}', -- extra
    'JONATHAN ROBINSON', -- proposer name
    'jonathan.robinson33@yahoo.com', -- proposer contact
    '', -- proposer URL
    'Central American residency, knowledge of Tesla''s & Solar technology, 10y+ engineering & project management, 5y+ entrepreneurship experience', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    324126,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Develop the KEVM & IELE',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '25000000000', -- funds
    'http://ideascale.com/t/UM5UZBbGi', -- url
    '', -- files_url
    218, -- impact_score
    '{"problem": "The move from Solidity to Plutus is a barrier to entry for many developers interested in Cardano. How do we facilitate the transition?", "solution": "Allocate treasury funds to revitalize development of the KEVM and IELE frameworks."}', -- extra
    'Kodex Data', -- proposer name
    'kodex.data@gmail.com', -- proposer contact
    'https://github.com/kframework/evm-semantics/', -- proposer URL
    'https://runtimeverification.com/', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    324066,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Whi World MMORPG',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '94999000000', -- funds
    'http://ideascale.com/t/UM5UZBbFj', -- url
    '', -- files_url
    230, -- impact_score
    '{"problem": "There are not enough open-source multiplayer game engines that are easy to pick up and start creating.", "solution": "Open-source multiplayer game engine. Which everyone can download and configure as they see fit."}', -- extra
    'Tevo', -- proposer name
    'tevosaks@gmail.com', -- proposer contact
    'https://github.com/whitevo/Whi-World-Data', -- proposer URL
    'I have had extensive background writing game scripts to create systems or automated processes. I am here because of the open-source game.', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    324032,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Credmark Credit Score',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '500000000000', -- funds
    'http://ideascale.com/t/UM5UZBbFA', -- url
    '', -- files_url
    263, -- impact_score
    '{"problem": "No financial system can exist without credit. Credit cannot be extended without credit data. Crypto credit doesn''t exist.", "solution": "Credmark uses crypto credit events to produce credit data for blockchain addresses. This provides credit for both DeFi and CeFi products."}', -- extra
    'paul', -- proposer name
    'paul@credmark.com', -- proposer contact
    'https://credmark.com', -- proposer URL
    'Credmark''s founders have roots in both traditional finance and crypto. One was CTO of a company acquired by FICO.', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    324023,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Decentralized Multiplayer RPG',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '600000000000', -- funds
    'http://ideascale.com/t/UM5UZBbE1', -- url
    '', -- files_url
    302, -- impact_score
    '{"problem": "The Cardano blockchain is not widely adopted and there needs to be leading examples of how to apply decentralized Apps on it.", "solution": "We propose a simple turn-based multiplayer RPG whose game rules and assets are governed entirely by blockchain metadata."}', -- extra
    'Beaver (BEAVR)', -- proposer name
    'twn.sham@gmail.com', -- proposer contact
    '', -- proposer URL
    'Our team has software engineering (10+ years and Masters of Engineering) plus game development experience.', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    324004,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Decentralized support',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '500000000000', -- funds
    'http://ideascale.com/t/UM5UZBbEi', -- url
    '', -- files_url
    133, -- impact_score
    '{"problem": "End user get scammed too often does not have a place to solve daily issues, most of people die not have the knowledge to solve wallet issues", "solution": "A decentralize platform that bring together expert people willing to help and users needing that help"}', -- extra
    'Franklincruzgarcia', -- proposer name
    'Franklincruzgarcia@gmail.com', -- proposer contact
    '', -- proposer URL
    'Web dev, Dapp dev, Haskell, Plutua', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    323986,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'ArtDapp - Powered by Cardano',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '650000000000', -- funds
    'http://ideascale.com/t/UM5UZBbEP', -- url
    '', -- files_url
    128, -- impact_score
    '{"problem": "An estimated 40% of investment grade art in circulation if fake or fraudulent.\n\nGlobal Art Market is $70 billion annual industry.", "solution": "Authentication via uninterrupted provenance chain combined with identity and digital image recognition should be the industry standard."}', -- extra
    'Bojan', -- proposer name
    'bojan@artdapp.io', -- proposer contact
    '', -- proposer URL
    'Currently there is no easy solution to transfer the provenance from one owner to the next.', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    323980,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Wallet lottery to increase Fin. ID',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '400000000000', -- funds
    'http://ideascale.com/t/UM5UZBbEJ', -- url
    '', -- files_url
    196, -- impact_score
    '{"problem": "People without a fin. ID see no reason to join Cardano. Although we see the advantage, they don''t see it yet. Wallet lottery paves the way.", "solution": "Join Cardano Wallet-Lottery: 5\u20b3 for free, win money, get a financial ID & support charity.\n\nWant more? Become active with Cardano!"}', -- extra
    'erik', -- proposer name
    'erik@zebie.nl', -- proposer contact
    '', -- proposer URL
    'Over 25 years entrepreneurial experience in profit and non-profit. Now connected to an NGO with over 600 global projects (120M per year).', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    323977,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'ERP Platform for Business Economics',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '54999000000', -- funds
    'http://ideascale.com/t/UM5UZBbEG', -- url
    '', -- files_url
    215, -- impact_score
    '{"problem": "A lot of companies use legacy ERP systems.\n\nIntegration and automation take time per company.\n\nERP systems are costly to maintain", "solution": "Open-Source ERP platform for dapps that leverage Cardano products and architecture.  \n\nThe platform is governed by stakeholders."}', -- extra
    'Tevo', -- proposer name
    'tevosaks@gmail.com', -- proposer contact
    '', -- proposer URL
    'Overseeing engineering projects by organizing and controlling its project elements.

Designing and conducting software product tests.', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    323970,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Cardano for Mobile dApp Developers',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '300000000000', -- funds
    'http://ideascale.com/t/UM5UZBbD9', -- url
    '', -- files_url
    411, -- impact_score
    '{"problem": "While mobile wallets are pretty common, mobile dApps in the AppStores are still extremely rare due to the scarcity of developer tools.", "solution": "Turn mobile platforms into first-class citizens of dApps world:\n\n\\- Mobile SDKs\n\n\\- Mobile-first dApp experience\n\n\\- AppStores compatibility"}', -- extra
    'Daniel', -- proposer name
    'daniel@tesseract.one', -- proposer contact
    'https://tesseract.one/', -- proposer URL
    '\- building dApps since 2017

\- launched Tesseract (human-compatible dApps platform) in 2018

\- graduated dLab/Emurgo accelerator in NYC', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    323950,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'A SONG FOR CARDANO',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '100000000000', -- funds
    'http://ideascale.com/t/UM5UZBbDp', -- url
    '', -- files_url
    204, -- impact_score
    '{"problem": "Raising Awareness Of A Cause Is Always Hard In The Short Term But A Focused Community Song Could Spread The Word Like Wildfire .", "solution": "A SONG FOR CARDANO Will Spread The Word Of Cardano Like Wildfire With Its Original Community Based Song Approach And Catchy Visual Lyrics  \n\ud83c\udfbb"}', -- extra
    'Edward', -- proposer name
    'garethfinch@hotmail.com', -- proposer contact
    'https://www.twitch.tv/anewformofmusic', -- proposer URL
    'For The Last 3 Years I Have Been Building A NEW FORM OF MUSIC - Music Mixed With Blockchain - A 24 Hour Natural Music Based On Blockchain .', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    323948,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'WBP - World''s Best Publisher',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '280000000000', -- funds
    'http://ideascale.com/t/UM5UZBbDn', -- url
    '', -- files_url
    111, -- impact_score
    '{"problem": "Scientific discourse is broken. Most publications are wrong. Publishing companies are obsolete intermediaries and most people are left out.", "solution": "A side chain to store all types of intellectual property in encrypted form."}', -- extra
    'dantiberiucostin', -- proposer name
    'dantiberiucostin@gmail.com', -- proposer contact
    '', -- proposer URL
    'I have over 10 years of experience in chemistry research. https://www.linkedin.com/in/dan-tiberiu-costin-73045950/', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    323939,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Pet Registry dApp + ₳Pay API',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '133301000000', -- funds
    'http://ideascale.com/t/UM5UZBbDe', -- url
    '', -- files_url
    423, -- impact_score
    '{"problem": "Devs are inspired by successful apps and the tools needed to build them, by creating both we inspire and accelerate devs and their solutions", "solution": "\u20b3Pay API helps devs accept ADA payments on websites. Pet Registry dApp, built on \u20b3Pay, services a global audience in a cheaper, better way."}', -- extra
    'Franco', -- proposer name
    'staking@adaverse.com', -- proposer contact
    '', -- proposer URL
    'Full stack developer with over 16 years of commercial experience developing web apps.  
Stake pool operator since ITN - https://adaverse.com', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    323911,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Education and Information sharing',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '24990000000', -- funds
    'http://ideascale.com/t/UM5UZBbDB', -- url
    '', -- files_url
    194, -- impact_score
    '{"problem": "We need to find more Cardanians to help grow this network.", "solution": "I want to make Educational and informational videos. I want to share all the news about Cardano to the world. Cardanomint is the way."}', -- extra
    'James Rupe', -- proposer name
    'Cardanomint@gmail.com', -- proposer contact
    '', -- proposer URL
    'Building & Operating computers, working with video and editing software for years. I am a thespian and want to share Cardano with the world.', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    323886,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Ouroboros over RINA',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '100000000000', -- funds
    'http://ideascale.com/t/UM5UZBbCm', -- url
    '', -- files_url
    307, -- impact_score
    '{"problem": "As transactions increase on the Cardano network, every node cannot relay every message utilizing the current TCP/IP architecture.", "solution": "Deploy a proof of concept stake pool and relay solution of Ouroborus over RINA using Ethernet/WDM at two sites in Tokyo, Japan."}', -- extra
    'jason.clark.durham', -- proposer name
    'jason.clark.durham@gmail.com', -- proposer contact
    '', -- proposer URL
    'Our sponsor is an innovative Japanese communications service provider currently deploying and experimenting with RINA.', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    323861,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Fandom Auction and Sales Platform',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '250000000000', -- funds
    'http://ideascale.com/t/UM5UZBbCM', -- url
    '', -- files_url
    152, -- impact_score
    '{"problem": "We would like to completely rebuild our sales platform with a focus on security, stability, and interactivity with the Cardano blockchain.", "solution": "Fund2 can assist us in acquiring the necessary resources to hire professionals to code our new platform and write smart contracts."}', -- extra
    'David Kanaszka Jr.', -- proposer name
    'David.kanaszka@gmail.com', -- proposer contact
    'https://www.TheDealersDen.com', -- proposer URL
    'Website Management, Community Management, Customer Support, Dispute Resolution, Marketing, Graphic Design, Blockchain Research, Business.', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    323851,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Independent token-incentive blogs',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '38000000000', -- funds
    'http://ideascale.com/t/UM5UZBbCC', -- url
    '', -- files_url
    133, -- impact_score
    '{"problem": "It''s should be easier for public to publish news / blog articles and on top of that to get proper amount of attention from the audience.", "solution": "I would like to build an app for both readers and writers, where a reader has a motivation to spend app tokens on articles he reads."}', -- extra
    'afatoga', -- proposer name
    'afatoga@gmail.com', -- proposer contact
    '', -- proposer URL
    'I am a fullstack developer (nodejs, react, php, wordpress)', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    323823,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Funding of Cardanojournal.com',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '100000000000', -- funds
    'http://ideascale.com/t/UM5UZBbBk', -- url
    '', -- files_url
    278, -- impact_score
    '{"problem": "Funding for the cardanojournal.com project. It is an experiment regarding the rewarding of the community for content creation.", "solution": "We would like to pay the chief-editor and the authors of the content."}', -- extra
    'Cardanians', -- proposer name
    'satuchac@gmail.com', -- proposer contact
    'https://cardanians.io/en', -- proposer URL
    'We have written many articles for Cardanians. Besides that, we had a private crypto group where we have provided articles 2x a week.', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    323787,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Cardano Community Council (CCC)',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '500000000000', -- funds
    'http://ideascale.com/t/UM5UZBbA9', -- url
    '', -- files_url
    122, -- impact_score
    '{"problem": "Community driven initiatives & priorities can''t rely on the CF, yet decentralised groups lack the focus a structured organisation provides.", "solution": "The CCC will be a transparent elected group formed to coordinate community driven adoption initiatives & actions through targeted committees"}', -- extra
    'Phil Lewis', -- proposer name
    'phil.lewis@vakatini.com', -- proposer contact
    '', -- proposer URL
    'More than 10 years leading and contributing to various different community groups.', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    323781,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Cardano Podcast in Spanish',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '145000000000', -- funds
    'http://ideascale.com/t/UM5UZBbA3', -- url
    '', -- files_url
    329, -- impact_score
    '{"problem": "In 2020 LATAM registered the most cryptocurrency users in the world with a mere limited English proficiency (EPI) of 50.34% on average.", "solution": "Create a comprehensive podcast in Spanish to expose Cardano to new audiences in order to incentivise the use blockchain technology in LATAM."}', -- extra
    'galborta', -- proposer name
    'galborta@quierotengo.bo', -- proposer contact
    'https://www.youtube.com/watch?v=XQH5vUnMv7k', -- proposer URL
    'A video production company with over 20 years of experience in the film industry working with major telecom franchises such as Millicom.', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    323778,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Cardano and FP in Malawi',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '500000000000', -- funds
    'http://ideascale.com/t/UM5UZBbA0', -- url
    '', -- files_url
    246, -- impact_score
    '{"problem": "Malawi is a poor nation with a large young population. Heavy reliance on foreign aid. Need for more innovative thinking. Not many exports.", "solution": "My plan is to teach functional programming in Malawi, give people access to a global market, and ignite tech culture at a grassroots level."}', -- extra
    'Ken Stanton', -- proposer name
    'this.tent@gmail.com', -- proposer contact
    'https://github.com/thistent', -- proposer URL
    '6 Months living in Malawi. 15 years working with Malawians to achieve goals in their communities. 25 years as a hobbyist programmer.', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    323761,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Cardano Social & Economic Ecosystem',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '340000000000', -- funds
    'http://ideascale.com/t/UM5UZBbAj', -- url
    '', -- files_url
    187, -- impact_score
    '{"problem": "There is no social platform to buy and sell items using ADA", "solution": "Create a social network with a mix of the old AOL chat rooms and Facebook with a market to buy and sell items with ADA"}', -- extra
    'goldkey0070', -- proposer name
    'goldkey0070@yahoo.com', -- proposer contact
    'https://github.com/goldkey0070', -- proposer URL
    'I''ve built many websites and I''m good at SEO. I''m great at advertising.

I''ve mostly programmed BTC Faucets. I would hire help.', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    323717,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Cardano Content Factory',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '30000000000', -- funds
    'http://ideascale.com/t/UM5UZBa90', -- url
    '', -- files_url
    374, -- impact_score
    '{"problem": "Content Creatr = popular proposals\n\nProposal overwhelm drowns-out tech builds.\n\nPods & Dapps compete needlesly\n\nhttps://youtu.be/UKH0ZZmVxkU", "solution": "Optimize content funding with a low risk, KPI-driven Guild.\n\nAuditing organization-> value-engineer content best practices, funding, output."}', -- extra
    'Miguel "Why Cardano" Orozco', -- proposer name
    'orozco3@gmail.com', -- proposer contact
    '', -- proposer URL
    'Cardano-Focused Youtube Channel 1+ year

\- 20% engagement KPIs (5x the Youtube avg)

V.E''d:

Podcast Starts: ~$500

Video Starts: ~$2000', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    323632,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Torus: Governance for Open-Source',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '150000000000', -- funds
    'http://ideascale.com/t/UM5UZBa8c', -- url
    '', -- files_url
    294, -- impact_score
    '{"problem": "It should be possible to make a living contributing to open-source, but open-source suffers from pervasive instability and lack of funding.", "solution": "Create a graphical DApp to manage open source governance, including consensus and funding"}', -- extra
    'Chad', -- proposer name
    'chad@torusonline.llc', -- proposer contact
    'https://github.com/torus-online/torus/', -- proposer URL
    'Chad Kirby is a product manager and engineer with real-world experience developing B2B SaaS software products and business models.', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    323566,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Further development of ADApools.org',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '250000000000', -- funds
    'http://ideascale.com/t/UM5UZBa7W', -- url
    '', -- files_url
    380, -- impact_score
    '{"problem": "Further development of ADApools to satisfy users, operators and devs needs and be inline with the Cardano roadmap.", "solution": "Adapools.org is probably the most visited tool that helps delegators from the ITN."}', -- extra
    'ADApools.org', -- proposer name
    'josef@cardanians.io', -- proposer contact
    'https://adapools.org', -- proposer URL
    'Adapools.org

adapools telegram bot, adapools twitter bot

adapools mobile apps', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    323553,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Japan Cardano Governance Association-Meetings & Communities & Podcasts',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '3500000000', -- funds
    'http://ideascale.com/t/UM5UZBa7J', -- url
    '', -- files_url
    385, -- impact_score
    '{"problem": "Ideal \\[Pre-sale 95% Sales destination Japanese voter advisor + There should be a lot of comments on the proposal\\] \u2192 Reality \\[Of 162 people in the Japan ADA holder questionnaire, 0 prospective advisors, 62% answered that the vote itself is incomprehensible. Japanese Governance Community and Fund 1 No comment, obfuscated by Google Translate display\\]", "solution": "\u624b\u6bb5\\[1\u30d5\u30a1\u30f3\u30c91\u4ee5\u4e0a\u30aa\u30f3\u30e9\u30a4\u30f3/\u30aa\u30d5\u30e9\u30a4\u30f3\u30df\u30fc\u30c8\u30a2\u30c3\u30d7\u958b\u50ac\u3001\u90311\u4ee5\u4e0a\u30ac\u30d0\u30ca\u30f3\u30b9\u30dd\u30c3\u30c9\u30ad\u30e3\u30b9\u30c8\u3001\u6bce\u65e5\u30ac\u30d0\u30ca\u30f3\u30b9\u7279\u5316\u30b3\u30df\u30e5\u30cb\u30c6\u30a3\u904b\u55b6\\]\u2192\u30b4\u30fc\u30eb\\[\u30d5\u30a1\u30f3\u30c95\uff1a\u53c2\u52a0\u738750\uff05\u8d85\u3001\u30a2\u30c9\u30d0\u30a4\u30b63\u4eba\u8d85\u3001\u65e5\u672c\u4eba\u8b70\u8ad6\u53c2\u52a0\u65701\u63d0\u6848\u3042\u305f\u308a3\u4eba\u8d85\\]"}', -- extra
    'yutazzz', -- proposer name
    'yutacreate@gmail.com', -- proposer contact
    'https://docs.google.com/document/d/1GR7aQVQCH59stqi3gthd7I6mMFFBGH-G6bW1UhnyRo8/edit?usp=sharing', -- proposer URL
    'オンラインオフラインミートアップ主催or講師参加10回以上、7つのコミュニティチャット設立運営、150以上YouTube動画作成、コンテンツクリエイター＋翻訳アンバサダ。', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    323526,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'An ultra efficient blockchain',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '75000000000', -- funds
    'http://ideascale.com/t/UM5UZBa6s', -- url
    '', -- files_url
    321, -- impact_score
    '{"problem": "Many developers and entrepreneurs build on proof-of-work blockchains that are using massive amount of energy.", "solution": "We want to create a short animation telling the story of why an ultra efficient blockchain matters to humanity, the planet and the future."}', -- extra
    'Big J', -- proposer name
    'brievendoosje@gmail.com', -- proposer contact
    '', -- proposer URL
    'We create outstanding animations for companies and organisations. Check out our websites www.jurjenbosklopper.nl and www.wouw.com', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    323433,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Cardano Mobile App',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '92714000000', -- funds
    'http://ideascale.com/t/UM5UZBa5L', -- url
    '', -- files_url
    300, -- impact_score
    '{"problem": "Developers and Business need a communication platform that delivers what they need for adoption.", "solution": "Cardano Mobile will consolidate the information being provided from various sources into one place and inform developers and business."}', -- extra
    'Chris Patten-Walker', -- proposer name
    'mail@chris-patten-walker.co.uk', -- proposer contact
    '', -- proposer URL
    '20+ years in the Financial Industry running teams and developing applications for Top Tier Banks.', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    323408,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'A Smart Market Toolkit for Cardano',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '981319000000', -- funds
    'http://ideascale.com/t/UM5UZBa4w', -- url
    '', -- files_url
    405, -- impact_score
    '{"problem": "A killer application, specific to Cardano is needed to drive wide-scale adoption", "solution": "Construct a toolkit for building Smart Markets, the killer dApps on Cardano. You can then trade any mix of assets tokenized as NFTs"}', -- extra
    'Robert O''Brien', -- proposer name
    'rsobrien@gmail.com', -- proposer contact
    'https://t.me/Smart_Market_for_NFTs', -- proposer URL
    'Financial markets software engineering, tech start-ups, Data & Govtech, impact investing, art, music. Active organizing legal-tech community', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    323396,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Incentivized knowledge sharing',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '250000000000', -- funds
    'http://ideascale.com/t/UM5UZBa4k', -- url
    '', -- files_url
    200, -- impact_score
    '{"problem": "Interesting people get overloaded with comments on social media. Important and urgent questions often don''t get the deserved attention.", "solution": "Ask anything and attach a small crypto donative in ADA to boost your visibility. A smart contract guarantees an answer or your money back."}', -- extra
    'Paulo Santos', -- proposer name
    'pjcs.pro@gmail.com', -- proposer contact
    'https://www.payma.co/', -- proposer URL
    'I''ve been creating mobile apps for the past 7 years for clients word-wide. I have experience on remote work and project management.', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    323346,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Ethereum to/from Cardano Bridge',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '50000000000', -- funds
    'http://ideascale.com/t/UM5UZBa3v', -- url
    '', -- files_url
    221, -- impact_score
    '{"problem": "To bridge between legacy chains to new ones is what is desired\n\nThe lack of an existing bridge to Cardano from Ethereum is the problem", "solution": "Creating a router between functioning smart contracts on separate chains, allowing a router to communicate between them securely."}', -- extra
    'smurf123444', -- proposer name
    'smurf123444@gmail.com', -- proposer contact
    '', -- proposer URL
    'https://github.com/smurf123444/', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    323284,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Cardano Hub',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '888888000000', -- funds
    'http://ideascale.com/t/UM5UZBa2u', -- url
    '', -- files_url
    183, -- impact_score
    '{"problem": "The existence of Cardano Hub will help community building, ADA adoption, involvement of developers and entrepreneurs into Cardano ecosystem", "solution": "Cardano Hub - your key to the future. Hub will include meetup space, co-working, library, media, cafe, bookstore, startup accelerator, etc."}', -- extra
    'Andrii Voloshyn', -- proposer name
    'cryptotexty@gmail.com', -- proposer contact
    '', -- proposer URL
    'In 2019 I created the literature crypto-bar Knygarium, which existed for half a year, had its own token and popularised crypto technology', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    323280,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Cardano Media Projects',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '94000000000', -- funds
    'http://ideascale.com/t/UM5UZBa2q', -- url
    '', -- files_url
    275, -- impact_score
    '{"problem": "There is a problem with media in general, and with crypto-media in particular. A lot of fake news, biases, lack of research, etc.", "solution": "Create and distribute content - video programs, and then text versions based on them."}', -- extra
    'Andrii Voloshyn', -- proposer name
    'cryptotexty@gmail.com', -- proposer contact
    '', -- proposer URL
    'I have 3+ years of experience in creating crypto-related content (text and video program) and managing small crypto media.', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    323267,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Small Sat Telescopes on ride share.',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '500000000000', -- funds
    'http://ideascale.com/t/UM5UZBa2d', -- url
    '', -- files_url
    133, -- impact_score
    '{"problem": "Large satellite constellations are wreaking havoc on Astronomy Research, at the same time the benefit to the rural and poor is incalculable.", "solution": "Small Sat based Telescopes, built with off the shelf components, launched as ride share on SpaceX rockets."}', -- extra
    'jondepinet', -- proposer name
    'jondepinet@gmail.com', -- proposer contact
    '', -- proposer URL
    'My primary background is in logistics, I have worked at the engineering level for an Observatory also at the logistics level for SpaceX.', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    323251,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Address Gap in SPO Education/Comms',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '100000000000', -- funds
    'http://ideascale.com/t/UM5UZBa2M', -- url
    '', -- files_url
    348, -- impact_score
    '{"problem": "A significant gap exists with the availability of critical, concise and thorough educational content targeting Cardano stake pool operators", "solution": "Create high value content targeting SPOs and establish communication channels bridges to enable effective dissemination and feedback to CF"}', -- extra
    'Kyle Solomon [FROG]', -- proposer name
    'ksolomon@adosia.com', -- proposer contact
    'https://spocra.io', -- proposer URL
    'The SPOCRA body consists of highly experienced stake pool operators possessing a broad range and depth of skillsets', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    323158,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Create message signing standard',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '5000000000', -- funds
    'http://ideascale.com/t/UM5UZBa0q', -- url
    '', -- files_url
    476, -- impact_score
    '{"problem": "Prove reserves, identity, delegating to a pool and more.", "solution": "Implement our specification you can find here: https://github.com/Emurgo/EmIPs/pull/5 (see \"previous work\" section for more information)"}', -- extra
    'sebastiengllmt', -- proposer name
    'sebastiengllmt@gmail.com', -- proposer contact
    'https://github.com/Emurgo/EmIPs/pull/5', -- proposer URL
    'We already wrote the specification and all the libraries required to do this project and can integrate in it Yoroi', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    323128,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'FOX Rewards Fitness & Mental Health',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '105700000000', -- funds
    'http://ideascale.com/t/UM5UZBa0L', -- url
    '', -- files_url
    279, -- impact_score
    '{"problem": "Through a \"proof-of-self-work\" gamification system I want to reward people of all abilities to improve Fitness, Mental Health & Mindfulness", "solution": "Helping to improve mental fitness through a family/self-funded project to try and change lives forever"}', -- extra
    'Rob Greig', -- proposer name
    'rob@foxrewards.co.uk', -- proposer contact
    'http://www.foxrewards.co.uk/', -- proposer URL
    'Entrepreneur 25+ years in desktop/web/cloud/mobile/data development, building, mentoring greenfield agile teams and transforming companies', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    323106,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    '''Beef chain'' for Medical Devices',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '300000000000', -- funds
    'http://ideascale.com/t/UM5UZBazz', -- url
    '', -- files_url
    173, -- impact_score
    '{"problem": "Healthcare costs are SKYrocketing making access to healthcare difficult for many. This should and can be changed asap.", "solution": "Blockchain for Medical Devices, tracking,traceability,inventory management,patient safety,Innovation,supply chain mngmnt,investment opps"}', -- extra
    'pbekink', -- proposer name
    'pbekink@yahoo.ca', -- proposer contact
    '', -- proposer URL
    'My passion is to work in the Medical Device industry which I have been doing now for 15 years

I have been working in Sales & Marketing jobs', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    323091,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Advertising Cardano',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '70000000000', -- funds
    'http://ideascale.com/t/UM5UZBazk', -- url
    '', -- files_url
    364, -- impact_score
    '{"problem": "The best materials promoting Cardano are very often hidden within long presentations; remaining unseen to a wider audience.", "solution": "I love finding these gems and turning them into short, inspirational, accessible videos that can be shared on YouTube and other platforms."}', -- extra
    'Andrew Ponton', -- proposer name
    'astra-pool@protonmail.com', -- proposer contact
    'https://www.astra-pool.com/', -- proposer URL
    '10 years of experience as a video editor. 2 film degrees and I have already made examples:

http://ow.ly/1uQf50BAX1y (YouTube playlist)', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    323055,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Index Dapps & Smart Contracts',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '200000000000', -- funds
    'http://ideascale.com/t/UM5UZBay9', -- url
    '', -- files_url
    157, -- impact_score
    '{"problem": "Consolidate & review by centralising a software repository to reduce the Development & Deployment Cycles for novice & intermediate Devs.", "solution": "Create a Website & Social Media Channel to Index & Review Dapps & Open Source Smart Contracts for reuse as Templates by third Parties."}', -- extra
    'Lotto', -- proposer name
    'support@lottopool.cloud', -- proposer contact
    '', -- proposer URL
    'Website Developer & Pool Operator who understands the business needs for a reviewed repository of Open Sourced Smart Contract templates.', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    322909,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Decentralized Cloud Platform',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '225000000000', -- funds
    'http://ideascale.com/t/UM5UZBawl', -- url
    '', -- files_url
    313, -- impact_score
    '{"problem": "IT Infrastructure services are becoming hyper-consolidated over the past 10 years since the word \"cloud\" entered the common vocabulary.", "solution": "dCloud using DLT technology and Cardano will empower everyone, individuals and large enterprises alike to provide cloud services."}', -- extra
    'mstopka', -- proposer name
    'mstopka@opensuse.org', -- proposer contact
    'https://discord.gg/97MwdEa', -- proposer URL
    'Our team has years of experience with Enterprise IT Infrastructure Products, incl. major brands like NetApp, Huawei, Fujitsu, HP…', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    322694,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'FOX Gifts & Fund Raising',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '122250000000', -- funds
    'http://ideascale.com/t/UM5UZBatE', -- url
    '', -- files_url
    281, -- impact_score
    '{"problem": "GoFundMe & JustGiving are fund raising sites - the processing fee is controversial. A low cost system that stakes funds would be better", "solution": "Collaboration with Stakepool owners to create a better solution to raising funds for personal events such as funerals, low income projects"}', -- extra
    'Rob Greig', -- proposer name
    'rob@foxrewards.co.uk', -- proposer contact
    '', -- proposer URL
    'I have been astonished at how much has been deducted by websites. This year £308k was deducted from £32M raised by Captain Tom for NHS in UK', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    322659,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'The We are Cardano Podcast',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '100000000000', -- funds
    'http://ideascale.com/t/UM5UZBasf', -- url
    '', -- files_url
    196, -- impact_score
    '{"problem": "The challenge of onboarding the general public is the fact that do not know who or what cardano is. We are just another tech project.", "solution": "A video podcast called \"We are Cardano Podcast\" It aims to put human faces to Cardano by speaking to anyone & everyone in the eco system."}', -- extra
    'marco', -- proposer name
    'marco@crypto2099.io', -- proposer contact
    'https://wearecardano.io/', -- proposer URL
    'I''m a people person. I''ve been in sales in some form since the 90s. This helps me take information & make it presentable to greater public.', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    322624,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Kaizen Crypto Cardano Podcast',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '162500000000', -- funds
    'http://ideascale.com/t/UM5UZBar5', -- url
    '', -- files_url
    326, -- impact_score
    '{"problem": "Developers that bring value to Cardano need a way to explain their ideas. We need a platform to stay updated with Goguen, Voltaire, etc.", "solution": "Create content that promotes discussion. The community can demo their projects & ideas to a wider audience. Grow awareness and adoption."}', -- extra
    'Pritesh Gosai', -- proposer name
    'kaizencryptocurrency@gmail.com', -- proposer contact
    'https://www.youtube.com/kaizencrypto', -- proposer URL
    'Cardano YouTube channel est 2019. Content ranges from news and updates, how-to videos, and podcasts where we host guest speakers.', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    322572,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Form a Haskell group on Gitcoin.',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '12345000000', -- funds
    'http://ideascale.com/t/UM5UZBarE', -- url
    '', -- files_url
    341, -- impact_score
    '{"problem": "We need to capitalize on Goguen, but our network is in its infancy, we need coordination w/ external s-contract devs to deploy use cases.", "solution": "I am looking to onboard Gitcoin as an environment with grants and preexisting network to catalyze the commission of proposals for dapps."}', -- extra
    'Michael', -- proposer name
    'koutonerslayer@gmail.com', -- proposer contact
    '', -- proposer URL
    'I have extensively studied digital sectors since 2011 and previously studied hardware modification/ electrical engineering.', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    322539,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Cardano in Spanish',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '60120000000', -- funds
    'http://ideascale.com/t/UM5UZBaqh', -- url
    '', -- files_url
    314, -- impact_score
    '{"problem": "Lack of Spanish content for the Cardano Project", "solution": "Provide video materials educating and keeping Hispanic community informed about the Cardano project"}', -- extra
    'Seba (Spanish Translator)', -- proposer name
    'cardanoencastellano@gmail.com', -- proposer contact
    'https://www.youtube.com/channel/UCf_fc4Qy1qVIO7A0pqU5AoQ', -- proposer URL
    '\+ 600 published videos (Youtube & LBRY)

+1.7k Subscribers  

+130k Total Views

+12k Total Watch time (hours)', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    322504,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Make Ada brand world recognised.',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '2000000000000', -- funds
    'http://ideascale.com/t/UM5UZBap7', -- url
    '', -- files_url
    111, -- impact_score
    '{"problem": "My idea is to sponsor an international Football team to make the ada logo/brand recognizable like the Btc logo .", "solution": "We will be solving the problem of main stream recognition and credibility.\n\nFootball is the most popular sport in the world."}', -- extra
    'oneredwan', -- proposer name
    'oneredwan@gmail.com', -- proposer contact
    '', -- proposer URL
    'The upcoming European Cup which was cancelled due to COVID-19 will be our goal. So we will try to sign a contract with a world class team.', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    322422,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Cardano Stake Pool Library',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '122000000000', -- funds
    'http://ideascale.com/t/UM5UZBaom', -- url
    '', -- files_url
    306, -- impact_score
    '{"problem": "Choosing a pool to stake your ADA to is confusing and there is no way to understand what each operator stands for without visiting each site", "solution": "The Cardano Stake Pool Library will offer summaries, category filtering etc to enable a better way to choose a pool that suits your values"}', -- extra
    'Rob Greig', -- proposer name
    'rob@foxrewards.co.uk', -- proposer contact
    '', -- proposer URL
    'Entrepreneur 25+ years in desktop/web/cloud/mobile/data development, building, mentoring greenfield agile teams and transforming companies', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    322391,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Easy remittance payments',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '10000000000', -- funds
    'http://ideascale.com/t/UM5UZBaoG', -- url
    '', -- files_url
    119, -- impact_score
    '{"problem": "Easy to use, transparent fees, affordable remittance payments anywhere in the world. From 1 currency to another.", "solution": "Tie fiat $ to an ADAstablecoin. Users can recieve/send $ on chain and draw the equivalent from the fiat pools sets up around the world."}', -- extra
    'Jhgross88', -- proposer name
    'Jhgross88@gmail.com', -- proposer contact
    '', -- proposer URL
    'None, but I have been struggling for a cheaper way to send remittance payments for the last 7 years. There has to be an easier way!', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    322378,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'ADA in 3055+ Bitcoin ATMs Globally!',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '120000000000', -- funds
    'http://ideascale.com/t/UM5UZBan3', -- url
    '', -- files_url
    329, -- impact_score
    '{"problem": "You cannot currently buy Cardano ADA from any Bitcoin ATMs. Boinnex owns and operates a network of Bitcoin ATMs and wants to add Ada support", "solution": "We will integrate ADA into the General Bytes Bitcoin ATM software. We will do this by developing an extension for ADA in the software."}', -- extra
    'bryan', -- proposer name
    'bryan@boinnex.com', -- proposer contact
    'https://boinnex.com/', -- proposer URL
    'We own a growing network of **Bitcoin ATMs**. We also run the **Cardano Abu** stake pool and have actively been involved in Cardano since 2017.', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    322377,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Trusted Sponsorship System',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '500000000000', -- funds
    'http://ideascale.com/t/UM5UZBan2', -- url
    '', -- files_url
    123, -- impact_score
    '{"problem": "Currently, there are problems with transparency, selection of sponsors, and lack of motivation for supporters to stand on their own feet.", "solution": "Develops an automatic sponsorship program when the sponsorship contract is written as a smart contact and meets the criteria for sponsorship"}', -- extra
    'Moon Suk Choi', -- proposer name
    'cromms@hanmail.net', -- proposer contact
    '', -- proposer URL
    'Ten years of corporate process innovation task involved.', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    322366,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Developer Acquisition Campaign',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '100000000000', -- funds
    'http://ideascale.com/t/UM5UZBanr', -- url
    '', -- files_url
    325, -- impact_score
    '{"problem": "Marketing alone may not reach all potential developers, direct cold contacting is an effective way to broaden reach.", "solution": "Lead a small team of sales professionals to pitch Cardano to potential developers, focusing on dev awareness and on-boarding."}', -- extra
    'Sam', -- proposer name
    'Sam@goodbyecarbon.org', -- proposer contact
    '', -- proposer URL
    '7+ Years of sales experience in a top performing team in my industry. Management/training experience.', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    322362,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Support Cardanoscan.io with Funds',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '900000000000', -- funds
    'http://ideascale.com/t/UM5UZBann', -- url
    '', -- files_url
    257, -- impact_score
    '{"problem": "Support diversity of tools for the decentralised cardano ecosystem. Cardanoscan explorer is the etherscan of cardano with rich data set.", "solution": "Cardanoscan.io is the most feature-rich explorer available for the Cardano blockchain. Support the development of the platform with funding"}', -- extra
    'Stitch Cardanoscan', -- proposer name
    'ashisherc@gmail.com', -- proposer contact
    'https://cardanoscan.io', -- proposer URL
    'I am a software architect, engineer, and creator of Cardanoscan.io', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    322338,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Liqwid:Cardano DeFi Lending Markets',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '385000000000', -- funds
    'http://ideascale.com/t/UM5UZBanO', -- url
    '', -- files_url
    426, -- impact_score
    '{"problem": "Instant borrow/lending markets are too expensive (cost, time, default risk) and users have no ability to monetize their credit/data.", "solution": "Open source DeFi lending app; automated liquidity pools so users can be the bank and govern the protocol with incentives to bootstrap credit"}', -- extra
    'Dewayne Cameron', -- proposer name
    'Dcameron@mfrconsultants.com', -- proposer contact
    'https://github.com/dewaynecam23?tab=repositories', -- proposer URL
    'Tweag.io: Built Cardano''s Smart Contract layer

Appinventiv.com: Top-rated Mobile app/dApp dev firm

30+ years combined Haskell + JavaScript', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    322327,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Defi Hackathon',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '250000000000', -- funds
    'http://ideascale.com/t/UM5UZBanD', -- url
    '', -- files_url
    259, -- impact_score
    '{"problem": "Ethereum has developed an ecosystem in the DeFi space, and their business models are choking on the Gas cost. Need them on Cardano.", "solution": "Developers, Project Managers, UI designers, graphic designers team together to solve a variety of DeFi building block type challenges."}', -- extra
    'joshjones2000', -- proposer name
    'joshjones2000@gmail.com', -- proposer contact
    '', -- proposer URL
    '30 years as an entrepreneur (Head of Operations - Head of Marketing), building businesses, running events from start to finish.', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    322325,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Lovelace Academy Marlowe Plutus',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '120740000000', -- funds
    'http://ideascale.com/t/UM5UZBanB', -- url
    '', -- files_url
    419, -- impact_score
    '{"problem": "**Attract**, **inspire** and **educate** builders and visionaries to build on top of Cardano''s game-changing Smart Contracts & Native Assets Platform", "solution": "++*Cardano''s Smarter Contracts Series:*++ Marlowe and Plutus + GitHub Tutorials\n\n++*Making Sense of Cardano Series:*++ Using Cardano in the real-world"}', -- extra
    'Maria Carmo', -- proposer name
    'canaltresseisnove@gmail.com', -- proposer contact
    '', -- proposer URL
    'Team of 3 SPOs with intimate knowledge on Cardano

A popular YouTube educator

Two Developers with many years experience training other devs', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    322314,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'ENVLP - a wallet with plug-ins',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '354812000000', -- funds
    'http://ideascale.com/t/UM5UZBam0', -- url
    '', -- files_url
    360, -- impact_score
    '{"problem": "Official cardano wallets are limited in the features and usefulness they provide. Our wallet will support plugins with functions people need", "solution": "To create a wallet with support for plug-ins developed and maintained by the community. Need a feature? Install a plug-in or create one."}', -- extra
    'Jeronimo Backes', -- proposer name
    'jbax@univocity.com', -- proposer contact
    'https://github.com/uniVocity/free-commerce', -- proposer URL
    '20+ years of software development experience, masters degree in computer science and a creator of multiple open-source projects.', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    322288,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Free-Commerce: sell online with ADA',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '724437000000', -- funds
    'http://ideascale.com/t/UM5UZBama', -- url
    '', -- files_url
    383, -- impact_score
    '{"problem": "Enabling stores to sell goods and services for ADA requires intermediaries who have control over your money and charge fees and commissions.", "solution": "To build opensource, intermediary and commission free payment integrations for Shopify stores. ADA flows directly from buyer to seller."}', -- extra
    'Jeronimo Backes', -- proposer name
    'jbax@univocity.com', -- proposer contact
    'https://github.com/uniVocity', -- proposer URL
    '20+ years of software development experience, masters degree in computer science and a creator of multiple open-source projects.', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    322286,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'THE PYNE FUND',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '35000000000', -- funds
    'http://ideascale.com/t/UM5UZBamX', -- url
    '', -- files_url
    268, -- impact_score
    '{"problem": "Traditional fundraising methods for Cardano startups, non-profits and social good projects is too cumbersome, opaque and high-risk.", "solution": "Stake pools operated for Cardano startups, charities, non-profits and \"social good\" projects."}', -- extra
    'Stephen Cameron', -- proposer name
    'stephen@levelondemand.com', -- proposer contact
    '', -- proposer URL
    'Stephen and Phil combine deep experience in network architecture/engineering, large-scale IT mgmt, biz dev and corporate finance.', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    322279,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Slot Leader Podcast',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '145000000000', -- funds
    'http://ideascale.com/t/UM5UZBamQ', -- url
    '', -- files_url
    282, -- impact_score
    '{"problem": "Business and finance professionals control large amounts of developer/financial resources, but have a tainted view of the blockchain space.", "solution": "Slot Leader aims to raise awareness about Cardano among business/finance professionals to consider building financial products on it."}', -- extra
    'Umed--[SKY] SkyLight Pool', -- proposer name
    'usaidov@gmail.com', -- proposer contact
    'https://www.youtube.com/c/SlotLeader', -- proposer URL
    '10+ years of investing experience+ professional network that spans the globe.', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    322275,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Decentralised Funding - Report',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '276644000000', -- funds
    'http://ideascale.com/t/UM5UZBamM', -- url
    '', -- files_url
    234, -- impact_score
    '{"problem": "**See PDF attached**\n\nDecentralised funding is a highly complicated system/process and we still need to figure out how to make it all work.", "solution": "**See PDF attached**  \n\nWe were involved in a similar project before which worked very well and ++**we can write out a report to learn from it.**++"}', -- extra
    'icoresearchgroup', -- proposer name
    'icoresearchgroup@gmail.com', -- proposer contact
    'https://icoresearchgroup.com/', -- proposer URL
    '**See PDF attached**

*   Experience with decentralised funding systems
*   Been in the Finance space for over a decade
*   Degree in Economics', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    322271,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'C₳ST Onboarding… 7 Billion + 🗺',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '200000000000', -- funds
    'http://ideascale.com/t/UM5UZBamI', -- url
    '', -- files_url
    191, -- impact_score
    '{"problem": "youtube / podcasts are inefficient and unsustainable. \ud83e\udd14", "solution": "the contextually curated, collaborative and conversational #cryptocurrency content C\u20b3ST. \ud83d\ude0c"}', -- extra
    'A', -- proposer name
    'a.njenga@live.com', -- proposer contact
    'https://www.youtube.com/playlist?list=PLLV3lz7P7-ISiveoIez4Vt-GXc6wWB05N', -- proposer URL
    'my background/experience in web/graphic design, filmmaking to architecture, mean design thinking and storytelling are a core competency.', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    322250,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'ADA MakerSpace Podcast Series',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '136000000000', -- funds
    'http://ideascale.com/t/UM5UZBalx', -- url
    '', -- files_url
    407, -- impact_score
    '{"problem": "There are no new videos to help people learn how to build Smart Contracts that are up to date on using the Plutus and Marlowe Playgrounds", "solution": "One hour lessons anyone can watch for free that cover different aspects of using Haskell and the Playgrounds to build things on Cardano"}', -- extra
    'Boone Bergsma', -- proposer name
    'b.bergsma@wethinkitmattersinc.com', -- proposer contact
    'https://www.youtube.com/channel/UCuSE9NFS_Q7LcNBMTep217w', -- proposer URL
    'I have been paying a Haskell developer to learn Plutus and Marlowe and give me lessons & sharing lessons on YouTube and people like them', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    322241,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'PoolTool Platform Upgrade',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '210000000000', -- funds
    'http://ideascale.com/t/UM5UZBalo', -- url
    '', -- files_url
    338, -- impact_score
    '{"problem": "Cost-based ranking methods could lead to handful of low-cost operators dominating the Cardano network, reducing infrastructure diversity.", "solution": "Our platform will offer avenues to build businesses and applications on top of Cardano to differentiate SPOs by additional product offering."}', -- extra
    'Umed--[SKY] SkyLight Pool', -- proposer name
    'usaidov@gmail.com', -- proposer contact
    '', -- proposer URL
    'Umed Saidov, CFA--a finance professional

Mike Fullman--creator of pooltool.io

Gabor Peto--creator of mobile pooltool app

All SPOs.', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    322239,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'The Cardano Aura Podcast',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '150000000000', -- funds
    'http://ideascale.com/t/UM5UZBalm', -- url
    '', -- files_url
    346, -- impact_score
    '{"problem": "Talented people in this ecosystem have trouble promoting their websites, dApps, and projects that bring value to the Cardano ecosystem.", "solution": "I create a live podcast that promotes long form discussion where people can demo their projects and proposals to a wider audience."}', -- extra
    'Peyton(bigpey)', -- proposer name
    'peytonwinget@hotmail.com', -- proposer contact
    '', -- proposer URL
    'I have been creating YouTube videos for Cardano for over a year and I have a large enough audience to give their projects a platform.', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    322230,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'WeThinkItMatters Dapp Development',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '160000000000', -- funds
    'http://ideascale.com/t/UM5UZBald', -- url
    '', -- files_url
    256, -- impact_score
    '{"problem": "Brands spend over $500Billion a year trying to influence people, while at the same time Millions of people are starving, homeless, & in need", "solution": "Cause-Integrated Marketing PaaS leveraging themoney brands spend on advertising to create sustainable funding for causes impacting all of us"}', -- extra
    'Boone Bergsma', -- proposer name
    'b.bergsma@wethinkitmattersinc.com', -- proposer contact
    'https://wethinkitmatters.com/', -- proposer URL
    'Over 10 years of experience in marketing and nonprofit fundraising. And we have never lived in such a time of demand 4 corporate citizenship', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    322218,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Cardano Swift SDK',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '100000000000', -- funds
    'http://ideascale.com/t/UM5UZBalQ', -- url
    '', -- files_url
    334, -- impact_score
    '{"problem": "There are no open source Swift SDKs for interacting with the Cardano blockchain from Apple OS infrastructure.", "solution": "Cardano Swift SDK is an open source solution for interacting with the Cardano blockchain using Swift and ObjectiveC"}', -- extra
    'KXP', -- proposer name
    'ivanmanov@live.com', -- proposer contact
    'https://github.com/kxpone/cardano-swift', -- proposer URL
    'We are a Cardano SPO (KXP Pool);

We are a contributors of Verge Currency wallet written in Swift with 17k lines of code.', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    322208,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'CNTools - SPO tools and services',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '140000000000', -- funds
    'http://ideascale.com/t/UM5UZBalG', -- url
    '', -- files_url
    336, -- impact_score
    '{"problem": "An unhealthy network with reduced performance due to stake pool issues could discourage onboarding and developers from building on Cardano.", "solution": "Tools and services to help SPOs setup/manage stake pools reduces the risk of wrongly configured pools that cause chain density degradation."}', -- extra
    'Damjan Ostrelic', -- proposer name
    'dostrelic0112@gmail.com', -- proposer contact
    'https://github.com/cardano-community/guild-operators', -- proposer URL
    'Ola Ahlman - SPO since 2019 (ticker: AHL)

Built various SPO tools and scripts (CNTools, gLiveView, ITN installation script for JorManager)', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    322205,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'ABCD',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '335000000000', -- funds
    'http://ideascale.com/t/UM5UZBalD', -- url
    '', -- files_url
    394, -- impact_score
    '{"problem": "Opportunities for young African devs to learn at an elite level and get them everything they need to make their ideas and projects a reality", "solution": "African Developer Training (then Expertise) Centre specializing in the development,of core Cardano blockchain technologies and applications."}', -- extra
    'Joshua Akpan', -- proposer name
    'joshuaakpan8@gmail.com', -- proposer contact
    'https://poapool.com/', -- proposer URL
    'Team of ambassadors who co-founded PoA in 2019.  
PoA runs in the ITN since December 2019 and was "Pioneer" in the F&F Haskell TestNet.', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    322197,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Haskell/Plutus/Marlowe Education',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '181956000000', -- funds
    'http://ideascale.com/t/UM5UZBak5', -- url
    '', -- files_url
    380, -- impact_score
    '{"problem": "We want to ensure easy entry for incoming developers and entrepreneurs, yet there is little educational content for Haskell/Plutus/Marlowe.", "solution": "I want to create educational content that conveys complex information in a structured way supplemented with examples that inspire new ideas."}', -- extra
    'Damjan Ostrelic', -- proposer name
    'dostrelic0112@gmail.com', -- proposer contact
    'https://github.com/DamjanOstrelic/Cardano-Development-Materials', -- proposer URL
    'Developer with teaching experience at university level. My educational content on YouTube is receiving overwhelmingly positive feedback.', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    322195,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'Cardano Starter Kits + APIs',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '265000000000', -- funds
    'http://ideascale.com/t/UM5UZBak3', -- url
    '', -- files_url
    446, -- impact_score
    '{"problem": "High entry barriers for community members ready to contribute diverse experience and talents toward mainstream adoption of Cardano.", "solution": "Free, open source APIs & Project-Based Learning resources that empower people from different backgrounds to drive adoption of Cardano."}', -- extra
    'James Dunseith', -- proposer name
    'jamesdunseith@gmail.com', -- proposer contact
    'https://workshopmaybe.com/learn/cardano-starter-kits/', -- proposer URL
    'A developer, an educator, and a marketing professional who share a passion for equipping all people with tools for solving real problems.', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)
,
--sql
(
    322194,  -- id
    (SELECT row_id FROM objective WHERE id=0 AND event=2), -- objective
    'West Africa Decentralized Alliance',  -- title
    '',  -- summary
    'catalyst-simple', -- category - VITSS Compat ONLY
    '', -- Public Payment Key
    '297825000000', -- funds
    'http://ideascale.com/t/UM5UZBak2', -- url
    '', -- files_url
    390, -- impact_score
    '{"problem": "++*Despite Africa''s immense opportunities, West African businesses, devs & governments are unaware of Cardano*++ ++*potential to solve local problems*++", "solution": "Entrench Cardano''s cutting edge solutions in the region by engaging & equipping local communities to identify & remove barriers to adoption."}', -- extra
    'Mercy', -- proposer name
    'adomaa77@icloud.com', -- proposer contact
    'https://wadalliance.org', -- proposer URL
    '**++Team++**: Sales, Marketing, Project & nonprofit work experience in W/Africa. Project Management, Programming, Analytics, Design, Resource dev''t', -- relevant experience
    'None',  -- bb_proposal_id
    '{ "yes", "no" }' -- bb_vote_options - Deprecated VitSS compat ONLY.
)

;

