package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
	"time"

	"github.com/alecthomas/kong"
	"github.com/input-output-hk/catalyst-core/ci/pkg"
	"github.com/input-output-hk/catalyst-core/ci/pkg/executors"
	"github.com/input-output-hk/catalyst-core/ci/pkg/git_clients"
	"github.com/input-output-hk/catalyst-core/ci/pkg/parsers"
	"github.com/input-output-hk/catalyst-core/ci/pkg/scanners"
	"github.com/input-output-hk/catalyst-core/ci/pkg/util"
	"github.com/spf13/afero"
)

// TagTemplate is a template for generating image tags.
type TagTemplate struct {
	Hash      string
	Timestamp string
	Version   string
}

var cli struct {
	Images imagesCmd `cmd:"" help:"Find the images generated by an Earthfile target."`
	Scan   scanCmd   `cmd:"" help:"Scan for Earthfiles."`
	Tags   tagsCmd   `cmd:"" help:"Generate image tags with the current git context."`
}

type imagesCmd struct {
	JsonOutput bool   `short:"j" long:"json" help:"Output in JSON format"`
	Path       string `arg:"" help:"path to Earthfile" type:"path"`
	Target     string `required:"true" short:"t" help:"The target to search for images"`
}

func (c *imagesCmd) Run() error {
	parser := parsers.NewEarthlyParser()
	earthfile, err := parser.Parse(c.Path)
	if err != nil {
		return err
	}

	images, err := earthfile.GetImages(c.Target)
	if err != nil {
		return err
	}

	if c.JsonOutput {
		jsonImages, err := json.Marshal(images)
		if err != nil {
			return err
		}
		fmt.Println(string(jsonImages))
		return nil
	} else {
		for _, image := range images {
			fmt.Println(image)
		}
	}

	return nil
}

type scanCmd struct {
	JsonOutput bool     `short:"j" long:"json" help:"Output in JSON format"`
	Images     bool     `short:"i" long:"images" help:"Also output images for the target of each Earthfile (requires -t option)"`
	Paths      []string `arg:"" help:"paths to scan for Earthfiles" type:"path"`
	Target     string   `short:"t" help:"filter by Earthfiles that include this target" default:""`
}

func (c *scanCmd) Run() error {
	parser := parsers.NewEarthlyParser()
	scanner := scanners.NewFileScanner(c.Paths, parser, afero.NewOsFs())

	var files []pkg.Earthfile
	var err error
	if c.Target != "" {
		files, err = scanner.ScanForTarget(c.Target)
	} else {
		files, err = scanner.Scan()
	}

	if err != nil {
		return err
	}

	if c.Images {
		if c.Target == "" {
			return fmt.Errorf("the --images (-i) option requires the --target (-t) option")
		}

		var output = make(map[string][]string)

		for _, file := range files {
			images, err := file.GetImages(c.Target)
			if err != nil {
				return err
			}

			output[filepath.Dir(file.Path)] = images
		}

		if c.JsonOutput {
			var outFinal []interface{}
			for path, images := range output {
				out := struct {
					Images []string `json:"images"`
					Path   string   `json:"path"`
				}{
					Images: images,
					Path:   path,
				}
				outFinal = append(outFinal, out)
			}
			jsonOutput, err := json.Marshal(outFinal)
			if err != nil {
				return err
			}
			fmt.Println(string(jsonOutput))
		} else {
			for path, images := range output {
				fmt.Printf("%s %s\n", path, strings.Join(images, ","))
			}
		}

		return nil
	}

	if c.JsonOutput {
		var paths []string
		for _, file := range files {
			paths = append(paths, filepath.Dir(file.Path))
		}
		jsonFiles, err := json.Marshal(paths)
		if err != nil {
			return err
		}
		fmt.Println(string(jsonFiles))
	} else {
		for _, file := range files {
			fmt.Println(filepath.Dir(file.Path))
		}
	}

	return nil
}

type tagsCmd struct {
	TemplateString string `arg:"" help:"template for generating image tags" default:"{{ .Hash }}"`
}

func (c *tagsCmd) Run() error {
	executor := executors.NewLocalExecutor("git")
	client := git_clients.NewExternalGitClient(executor)

	// Collect the highest version from the git tags
	tags, err := client.Tags()
	if err != nil {
		return err
	}
	highest := util.GetHighestVersion(tags)

	// Get the current git commit hash
	hash, err := executor.Run("rev-parse", "HEAD")
	if err != nil {
		return err
	}

	// Get the current timestamp
	timestamp := time.Now().Format("20060102150405")

	// Generate the tag
	tmpl, err := template.New("tag").Parse(c.TemplateString)
	if err != nil {
		return err
	}

	data := TagTemplate{
		Hash:      hash,
		Timestamp: timestamp,
		Version:   highest,
	}
	err = tmpl.Execute(os.Stdout, data)
	if err != nil {
		return err
	}

	return nil
}

func main() {
	ctx := kong.Parse(&cli)
	err := ctx.Run()
	ctx.FatalIfErrorf(err)
	os.Exit(0)
}
