[package]
name = "cat-data-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { workspace = true }

tokio = { version = "1.8", features = ["rt", "macros"] }
thiserror = { version = "1.0" }
axum = { version = "0.6.9" }