VERSION 0.7

build:
    FROM ../../+builder
    RUN cargo build --locked --release --bin cat-data-service

    # Store the artifact
    SAVE ARTIFACT target/release/cat-data-service cat-data-service
    SAVE IMAGE --cache-hint

docker:
    FROM ../../+deployment

    WORKDIR /app
    ARG tag="latest"
    ARG registry

    COPY +build/cat-data-service .

    ENTRYPOINT ["/app/cat-data-service"]
    SAVE IMAGE ${registry}cat-data-service:$tag
