VERSION 0.7
FROM debian:bullseye-slim

WORKDIR /app

build:
    FROM ../../+build-workspace
    RUN cargo build --locked --release --bin cat-data-service
    # Store the artifact in a temporary directory, so that it can be used as a dependency
    SAVE ARTIFACT target/release/cat-data-service cat-data-service

docker:
    COPY +build/cat-data-service .
    ENTRYPOINT ["/app/cat-data-service"]
    SAVE IMAGE cat-data-service:latest
