VERSION 0.7

FROM debian:stable-slim

# BASH, CURL, GPG, NODEJS, NPM, JDK, JRE
dependencies:
    RUN apt-get update
    RUN apt-get install bash
    RUN apt-get install curl -y
    RUN apt-get install gpg -y
    RUN curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
    RUN apt-get install nodejs -y
    RUN apt-get install npm -y
    RUN apt-get install default-jre -y

generate-client:
    FROM +dependencies
    
    # TODO: GET RIGHT FILE FROM POEM GENERATION / BY COPY FILE IN REPO
    ARG openapispec_file="./petstore.yaml"
    COPY $openapispec_file .

    RUN npm install @openapitools/openapi-generator-cli -g

    RUN openapi-generator-cli validate -i $openapispec_file

    RUN openapi-generator-cli generate -i $openapispec_file -g rust -o ./tmp/client/ --package-name cat-data-service-client