# Set the Earthly version to 0.7
VERSION 0.7

FROM python:3.11-slim-bullseye
ENV PYTHONUNBUFFERED=true

# Install Poetry
RUN pip install poetry==1.4.2

# Set the working directory
WORKDIR /utilities/ideascale-importer

build:
    FROM scratch
    COPY --dir ideascale_importer pyproject.toml poetry.lock README.md ./
    SAVE ARTIFACT /utilities/ideascale-importer ideascale-importer

docker:
    ARG tag="latest"
    ARG registry

    # install system dependencies
    RUN apt-get update && \
        apt-get install -y --no-install-recommends libpq5
    ## apt cleanup
    RUN apt-get install -y --no-install-recommends && \
        apt-get clean && \
        rm -rf /var/lib/apt/lists/*

    COPY +build/ideascale-importer /utilities/ideascale-importer
    # Set the entrypoint to use the Poetry virtual environment
    ENTRYPOINT ["poetry", "run"]

    # Set the default command to run the main script
    CMD ["ideascale-importer", "--help"]

    SAVE IMAGE ideascale-importer:latest
