VERSION 0.7

build:
    FROM ../../../+build-workspace
    RUN with_nix cargo build --locked --release --bin catalyst-toolbox
    # Store the artifact in a temporary directory, so that it can be used as a dependency
    SAVE ARTIFACT target/release/catalyst-toolbox catalyst-toolbox

docker:
    FROM debian:bullseye-slim

    WORKDIR /app
    ARG tag="latest"
    ARG registry

    COPY +build/catalyst-toolbox .
    ENTRYPOINT ["/app/catalyst-toolbox"]
    SAVE IMAGE ${registry}catalyst-toolbox:$tag
