VERSION 0.7

build:
    FROM ../../../+builder
    RUN cargo build --locked --release --bin catalyst-toolbox

    # Store the artifact
    SAVE ARTIFACT target/release/catalyst-toolbox catalyst-toolbox
    SAVE IMAGE --cache-hint

docker:
    FROM ../../../+deployment

    WORKDIR /app
    ARG tag="latest"
    ARG registry

    # install dependencies
    RUN apt-get update && \
        apt-get install -y --no-install-recommends libpq5
    ## apt cleanup
    RUN apt-get install -y --no-install-recommends && \
        apt-get clean && \
        rm -rf /var/lib/apt/lists/*

    COPY +build/catalyst-toolbox .

    ENTRYPOINT ["/app/catalyst-toolbox"]
    SAVE IMAGE ${registry}catalyst-toolbox:$tag
