VERSION 0.7
FROM rust:1.68-alpine

WORKDIR /migrations

build:
    # Need these libs to build refinery
    RUN apk add --no-cache pcc-libs-dev musl-dev pkgconfig openssl-dev

    # Build it.
    RUN cargo install refinery_cli --version 0.8.7

    SAVE ARTIFACT /usr/local/cargo/bin/refinery refinery
    SAVE IMAGE --cache-hint

docker:
    # Create image from a fresh alpine
    FROM alpine:3.17
    ARG tag="latest"
    ARG registry

    WORKDIR /eventdb

    # Add the refinery CLI tool
    COPY +build/refinery .
    COPY --dir ../../src/event-db+build/setup ./setup
    COPY --dir ../../src/event-db+build/migrations ./migrations
    COPY --dir ../../src/event-db+build/historic_data ./historic_data
    COPY ../../src/event-db+build/refinery.toml .

    # Add the psql tool.
    RUN apk --no-cache add postgresql14-client

    VOLUME /eventdb/tmp
    COPY ./entry.sh .
    RUN chmod ugo+x ./entry.sh

    ENTRYPOINT ["./entry.sh"]

    # Push the container...
    SAVE IMAGE --push ${registry}migrations:$tag

test:
    WITH DOCKER \
        --load test:latest=+docker
        RUN docker run test:latest
    END
