VERSION 0.7

deps:
    FROM ../../+rust-toolchain

build:
    FROM +deps

    # Build refinery
    RUN cargo install refinery_cli --version 0.8.14 --locked --root .

    SAVE ARTIFACT ./bin/refinery refinery
    SAVE IMAGE --cache-hint

package:
    FROM debian:stable-slim
    ARG tag="latest"
    ARG data="historic"

    WORKDIR /eventdb

    # Add psql
    RUN apt-get update && \
        # Install dependencies needed for adding the key and postgres
        apt-get install -y --no-install-recommends \
          wget \
          gnupg2 \
          ca-certificates \
          lsb-release \
          apt-transport-https && \
        \
        # Create the keyring directory
        install -m 0755 -d /etc/apt/keyrings && \
        \
        # Download, de-armor, and save the PostgreSQL key
        wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | \
          gpg --dearmor -o /etc/apt/keyrings/postgresql.gpg && \
        \
        # Set permissions for the key
        chmod 644 /etc/apt/keyrings/postgresql.gpg && \
        \
        # Create the sources list, pointing to the key
        echo "deb [signed-by=/etc/apt/keyrings/postgresql.gpg] http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list && \
        \
        # Update apt and install postgresql
        apt-get update && \
        apt-get install -y --no-install-recommends postgresql-14 && \
        \
        # Clean up
        apt-get remove -y wget gnupg2 lsb-release apt-transport-https && \
        apt-get autoremove -y && \
        apt-get clean && \
        rm -rf /var/lib/apt/lists/*

    # Add refinery
    COPY +build/refinery .

    # Add migrations
    COPY --dir ../../src/event-db+build/setup ./setup
    COPY --dir ../../src/event-db+build/migrations ./migrations
    IF [ "$data" = "historic" ]
        COPY --dir ../../src/event-db+build/historic_data ./historic_data
        COPY ../../src/event-db+build/stage_data ./stage_data
    ELSE IF [ "$data" = "test" ]
        COPY --dir ../../src/event-db+build/test_data ./test_data
    END
    COPY ../../src/event-db+build/refinery.toml .

    VOLUME /eventdb/tmp
    COPY ./entry.sh .
    RUN chmod ugo+x ./entry.sh

    ENTRYPOINT ["./entry.sh"]
    SAVE IMAGE migrations:$tag
    
# TODO: Enable this when CI supports passing -P dynamically
# test:
#     FROM earthly/dind:alpine
#     WITH DOCKER \
#         --load test:latest=+docker
#         RUN docker run test:latest
#     END

docker:
    FROM +package

    ARG container='migrations'
    ARG tag="latest"

    SAVE IMAGE ${container}:${tag}