[package]
name = "loki"
description = "Loki is a simple command line tool that lets you deploy an adversarial Jormungandr node with a REST interface"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chain-addr      = { path = "../../../chain-libs/chain-addr", features = [ "property-test-api" ] }
chain-crypto    = { path = "../../../chain-libs/chain-crypto", features = [ "property-test-api" ] }
chain-core      = { path = "../../../chain-libs/chain-core" }
chain-impl-mockchain = { workspace = true }
jormungandr-automation = { path = "../jormungandr-automation" }
jormungandr-lib = { workspace = true }
thor = {path = "../thor"}
tokio = { version = "1.15", features = ["macros","rt","rt-multi-thread"] }
multiaddr = { package = "parity-multiaddr", version = "0.11" }
serde_yaml = "0.8.23"
serde = { version = "1.0", features = ["derive"] }
clap = { workspace = true }
custom_debug = "0.5"
thiserror = "1.0"
warp = "0.3"
rand = "0.8"
rand_core = "0.6"
reqwest = { workspace = true }
