[package]
name = "vit-servicing-station-lib"
version = "0.3.4-dev"
authors = ["danielsanchezq <daniel.sanchez@iohk.io>"]
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.33"
base64 = "0.13"
time = { version = "0.3", features = ["parsing", "formatting"] }
diesel = { version = "1.4.5", features = ["postgres", "r2d2", "64-column-tables", "serde_json"] }
diesel_migrations = "1.4.0"
dotenv = "0.15"
itertools = "0.10"
log = { version = "0.4.11", features = ["serde"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
strum = "0.24"
strum_macros = "0.24"
simplelog = "0.8.0"
clap = { workspace = true }
r2d2 = "0.8.10"
thiserror = "1.0.30"
tokio = { version = "1.18.0", features = ["macros", "signal", "rt", "fs", "sync"] }
tracing.workspace = true
tracing-futures.workspace = true
tracing-subscriber.workspace = true
warp = { version = "0.3.2", features = ["tls"] }
snapshot-lib = { path = "../../catalyst-toolbox/snapshot-lib" }
chain-ser = { path = "../../chain-libs/chain-ser" }
jormungandr-lib = { workspace = true }
event-db = { path = "../../event-db" }
eccoxide = { git = "https://github.com/eugene-babichenko/eccoxide.git", branch = "fast-u64-scalar-mul", features = ["fast-u64-scalar-mul"], optional = true }
http-zipkin = "0.3.0"
notify = "5"
url = { version = "2", features = ["serde"] }
tempfile = "3"

[dev-dependencies]
tempfile = "3"
rand = "0.8"
vit-servicing-station-tests = { path = "../vit-servicing-station-tests" }
pretty_assertions = "1.3"
