[package]
name = "jormungandr-automation"
version = "0.13.0"
authors = ["Nicolas Di Prima <nicolas.diprima@iohk.io>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "0.6"
prost = "0.9"
tokio = { version = "1.15", features = ["macros","rt","rt-multi-thread"] }
tokio-stream = "0.1"
futures = "0.3.21"
base64 = "0.13"
bech32 = "0.8"
bytesize = "1.1.0"
clap = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chain-impl-mockchain = { workspace = true, features = [ "property-test-api" ] }
chain-addr      = { path = "../../../chain-libs/chain-addr", features = [ "property-test-api" ] }
chain-core      = { path = "../../../chain-libs/chain-core" }
chain-crypto    = { path = "../../../chain-libs/chain-crypto", features = [ "property-test-api" ] }
chain-time      = { path = "../../../chain-libs/chain-time" }
chain-storage   = { path = "../../../chain-libs/chain-storage", features = ["with-bench"] }
chain-vote      = { path = "../../../chain-libs/chain-vote" }
cardano-legacy-address = { path = "../../../chain-libs/cardano-legacy-address" }
typed-bytes = { path = "../../../chain-libs/typed-bytes" }
jormungandr-lib = { workspace = true }
jcli = { path = "../../jcli" }
jortestkit = { path = "../../../jortestkit" }
rand = "0.8"
rand_core = "0.6"
rand_chacha = "0.3"
humantime = "2.0"
custom_debug = "0.5"
thiserror = "1.0"
poldercast = "1.2"
sysinfo = "0.26"
os_info = { version = "3.3.0", default-features = false }
zip = "0.6.0"
flate2 = "1.0.21"
tar = "0.4"
hex = "0.4"
lazy_static = "1"
serde_derive = "1.0"
assert_fs = "1.0"
serde_yaml = "0.8"
regex = "1.6"
fs_extra = "1.1.0"
url = "2.2.0"
graphql_client.workspace = true
semver = { version = "1.0", features = ["serde"] }
json = "0.12.4"
strum = { version = "0.24", features = ["derive"] }
tracing.workspace = true
log = { version = "0.4", features = ["serde"] }
netstat2 = "0.9"
multiaddr = { package = "parity-multiaddr", version = "0.11" }
keynesis = "1"
tempfile = "3"
assert_cmd = "2.0.4"
predicates = "2.0"
warp = "0.3"
reqwest = { workspace = true }

[dependencies.tracing-subscriber]
workspace = true
default-features = false
features = ["json","fmt"]


[features]
default = []
property-test-api = [ ]

[build-dependencies]
tonic-build = "0.6"
versionisator = "1.0.2"
