[package]
name = "blockchain"
version = "0.1.0"
authors = ["Nicolas Di Prima <nicolas.diprima@iohk.io>"]
edition = "2021"

[dependencies]
chain-impl-mockchain = { workspace = true }
chain-time           = { path = "../../../chain-libs/chain-time" }
thiserror = "1.0.30"
lru       = "0.7"
