version: "3"

services:
  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalystEventDev
      - PGPASSWORD=postgres
      - PGUSER=catalyst-event-dev
      - PGDATABASE=CatalystEventDev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 2s
      timeout: 5s
      retries: 10
    ports:
      - 5432:5432
    volumes:
      - eventdb:/var/lib/postgresql/data

  migrations:
    image: migrations:latest
    environment:
      # Required environment variables for migrations
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=CatalystEventDev
      - DB_SUPERUSER=postgres
      - DB_SUPERUSER_PASSWORD=postgres
      - DB_USER=catalyst-event-dev
      - DB_USER_PASSWORD=CHANGE_ME
      - ADMIN_ROLE_PASSWORD=CHANGE_ME
      - ADMIN_USER_PASSWORD=CHANGE_ME
      - ANON_ROLE_PASSWORD=CHANGE_ME
    depends_on:
      db:
        condition: service_healthy

  graphql:
    image: event-db-graphql:latest
    environment:
      - DATABASE_URL=postgres://catalyst-event-dev:CHANGE_ME@db/CatalystEventDev
      - JWT_SECRET=CHANGE_ME
      - GRAPHQL_PORT=5000
    ports:
      - 5000:5000
    depends_on:
      migrations:
        condition: service_completed_successfully

  cat-data-service:
    image: cat-data-service:latest
    environment:
      - DATABASE_URL=postgres://catalyst-event-dev:CHANGE_ME@db/CatalystEventDev
    depends_on:
      migrations:
        condition: service_completed_successfully
    ports:
      - 3030:3030

  leader0:
    image: voting-node:latest
    hostname: leader0
    depends_on:
      migrations:
        condition: service_completed_successfully
    environment:
      # Required env vars
      - IS_NODE_RELOADABLE=True
      - VOTING_HOST=0.0.0.0
      - VOTING_PORT=8000
      - VOTING_LOG_LEVEL=debug
      - VOTING_NODE_STORAGE=node_storage
      - EVENTDB_URL=postgres://catalyst-event-dev:CHANGE_ME@db/CatalystEventDev
      - JORM_PATH=jormungandr
      - JCLI_PATH=jcli
      ### SECRET GENERATION
      # The CRS is used to generate committee members, this is only used by leader0
      - COMMITTEE_CRS=COMMON-REFERENCE-STRING-USED-THAT-IS-SECRET
      - SECRET_SECRET=SUPER_SECRET_SECRET_THAT_MUST_BE_CHANGED
      ### EXTERNAL DATA IMPORTER
      - IDEASCALE_API_TOKEN=CHANGE_ME_FOR_A_PROPER_TOKEN
      - IDEASCALE_CAMPAIGN_GROUP=66
      - IDEASCALE_STAGE_ID=4385
      - IDEASCALE_LOG_LEVEL=debug
      - IDEASCALE_LOG_FORMAT=text
      - IDEASCALE_API_URL=https://cardano.ideascale.com
      ### SNAPSHOT TOOL DATA IMPORTER
      - SNAPSHOT_INTERVAL_SECONDS=60
      - SNAPSHOT_CONFIG_PATH=/app/snapshot-importer-example-config.json
      - SNAPSHOT_OUTPUT_DIR=/tmp/snapshot-output
      - SNAPSHOT_NETWORK_ID=testnet
      - SNAPSHOT_LOG_LEVEL=debug
      - SNAPSHOT_LOG_FORMAT=text
    volumes:
      - leader0_store:/node_storage
      - leader0_store:/tmp/snapshot-output
      - ./ideascale-importer-config.json:/app/ideascale-importer-config.json
      - ./snapshot-importer-example-config.json:/app/snapshot-importer-example-config.json

volumes:
  eventdb:
  leader0_store:
