// @generated automatically by Diesel CLI.

diesel::table! {
    /// Representation of the `challenge` table.
    ///
    /// (Automatically generated by Diesel.)
    challenge (row_id) {
        /// The `row_id` column of the `challenge` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        row_id -> Int4,
        /// The `id` column of the `challenge` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `election` column of the `challenge` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        election -> Int4,
        /// The `category` column of the `challenge` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        category -> Text,
        /// The `title` column of the `challenge` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        title -> Text,
        /// The `description` column of the `challenge` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        description -> Text,
        /// The `rewards_currency` column of the `challenge` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        rewards_currency -> Nullable<Text>,
        /// The `rewards_total` column of the `challenge` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        rewards_total -> Nullable<Int8>,
        /// The `proposers_rewards` column of the `challenge` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        proposers_rewards -> Nullable<Int8>,
        /// The `vote_options` column of the `challenge` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        vote_options -> Nullable<Int4>,
        /// The `extra` column of the `challenge` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        extra -> Nullable<Jsonb>,
    }
}

diesel::table! {
    /// Representation of the `challenge_category` table.
    ///
    /// (Automatically generated by Diesel.)
    challenge_category (name) {
        /// The `name` column of the `challenge_category` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `description` column of the `challenge_category` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        description -> Nullable<Text>,
    }
}

diesel::table! {
    /// Representation of the `community_advisors_review` table.
    ///
    /// (Automatically generated by Diesel.)
    community_advisors_review (row_id) {
        /// The `row_id` column of the `community_advisors_review` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        row_id -> Int4,
        /// The `proposal_id` column of the `community_advisors_review` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        proposal_id -> Int4,
        /// The `assessor` column of the `community_advisors_review` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        assessor -> Varchar,
        /// The `impact_alignment_rating_given` column of the `community_advisors_review` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        impact_alignment_rating_given -> Nullable<Int4>,
        /// The `impact_alignment_note` column of the `community_advisors_review` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        impact_alignment_note -> Nullable<Varchar>,
        /// The `feasibility_rating_given` column of the `community_advisors_review` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        feasibility_rating_given -> Nullable<Int4>,
        /// The `feasibility_note` column of the `community_advisors_review` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        feasibility_note -> Nullable<Varchar>,
        /// The `auditability_rating_given` column of the `community_advisors_review` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        auditability_rating_given -> Nullable<Int4>,
        /// The `auditability_note` column of the `community_advisors_review` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        auditability_note -> Nullable<Varchar>,
        /// The `ranking` column of the `community_advisors_review` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        ranking -> Nullable<Int4>,
    }
}

diesel::table! {
    /// Representation of the `config` table.
    ///
    /// (Automatically generated by Diesel.)
    config (row_id) {
        /// The `row_id` column of the `config` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        row_id -> Int4,
        /// The `id` column of the `config` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Varchar,
        /// The `id2` column of the `config` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        id2 -> Varchar,
        /// The `id3` column of the `config` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        id3 -> Varchar,
        /// The `value` column of the `config` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        value -> Nullable<Jsonb>,
    }
}

diesel::table! {
    /// Representation of the `contributions` table.
    ///
    /// (Automatically generated by Diesel.)
    contributions (row_id) {
        /// The `row_id` column of the `contributions` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        row_id -> Int4,
        /// The `stake_public_key` column of the `contributions` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        stake_public_key -> Text,
        /// The `snapshot_id` column of the `contributions` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        snapshot_id -> Int4,
        /// The `voting_key` column of the `contributions` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        voting_key -> Text,
        /// The `voting_weight` column of the `contributions` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        voting_weight -> Int4,
        /// The `voting_key_idx` column of the `contributions` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        voting_key_idx -> Int4,
        /// The `value` column of the `contributions` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        value -> Int8,
        /// The `voting_group` column of the `contributions` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        voting_group -> Text,
        /// The `reward_address` column of the `contributions` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        reward_address -> Nullable<Text>,
    }
}

diesel::table! {
    /// Representation of the `currency` table.
    ///
    /// (Automatically generated by Diesel.)
    currency (name) {
        /// The `name` column of the `currency` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `description` column of the `currency` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        description -> Nullable<Text>,
    }
}

diesel::table! {
    /// Representation of the `election` table.
    ///
    /// (Automatically generated by Diesel.)
    election (row_id) {
        /// The `row_id` column of the `election` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        row_id -> Int4,
        /// The `name` column of the `election` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `description` column of the `election` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        description -> Text,
        /// The `registration_snapshot_time` column of the `election` table.
        ///
        /// Its SQL type is `Nullable<Timestamp>`.
        ///
        /// (Automatically generated by Diesel.)
        registration_snapshot_time -> Nullable<Timestamp>,
        /// The `voting_power_threshold` column of the `election` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        voting_power_threshold -> Nullable<Int8>,
        /// The `max_voting_power_pct` column of the `election` table.
        ///
        /// Its SQL type is `Nullable<Numeric>`.
        ///
        /// (Automatically generated by Diesel.)
        max_voting_power_pct -> Nullable<Numeric>,
        /// The `start_time` column of the `election` table.
        ///
        /// Its SQL type is `Nullable<Timestamp>`.
        ///
        /// (Automatically generated by Diesel.)
        start_time -> Nullable<Timestamp>,
        /// The `end_time` column of the `election` table.
        ///
        /// Its SQL type is `Nullable<Timestamp>`.
        ///
        /// (Automatically generated by Diesel.)
        end_time -> Nullable<Timestamp>,
        /// The `insight_sharing_start` column of the `election` table.
        ///
        /// Its SQL type is `Nullable<Timestamp>`.
        ///
        /// (Automatically generated by Diesel.)
        insight_sharing_start -> Nullable<Timestamp>,
        /// The `proposal_submission_start` column of the `election` table.
        ///
        /// Its SQL type is `Nullable<Timestamp>`.
        ///
        /// (Automatically generated by Diesel.)
        proposal_submission_start -> Nullable<Timestamp>,
        /// The `refine_proposals_start` column of the `election` table.
        ///
        /// Its SQL type is `Nullable<Timestamp>`.
        ///
        /// (Automatically generated by Diesel.)
        refine_proposals_start -> Nullable<Timestamp>,
        /// The `finalize_proposals_start` column of the `election` table.
        ///
        /// Its SQL type is `Nullable<Timestamp>`.
        ///
        /// (Automatically generated by Diesel.)
        finalize_proposals_start -> Nullable<Timestamp>,
        /// The `proposal_assessment_start` column of the `election` table.
        ///
        /// Its SQL type is `Nullable<Timestamp>`.
        ///
        /// (Automatically generated by Diesel.)
        proposal_assessment_start -> Nullable<Timestamp>,
        /// The `assessment_qa_start` column of the `election` table.
        ///
        /// Its SQL type is `Nullable<Timestamp>`.
        ///
        /// (Automatically generated by Diesel.)
        assessment_qa_start -> Nullable<Timestamp>,
        /// The `snapshot_start` column of the `election` table.
        ///
        /// Its SQL type is `Nullable<Timestamp>`.
        ///
        /// (Automatically generated by Diesel.)
        snapshot_start -> Nullable<Timestamp>,
        /// The `voting_start` column of the `election` table.
        ///
        /// Its SQL type is `Nullable<Timestamp>`.
        ///
        /// (Automatically generated by Diesel.)
        voting_start -> Nullable<Timestamp>,
        /// The `voting_end` column of the `election` table.
        ///
        /// Its SQL type is `Nullable<Timestamp>`.
        ///
        /// (Automatically generated by Diesel.)
        voting_end -> Nullable<Timestamp>,
        /// The `tallying_end` column of the `election` table.
        ///
        /// Its SQL type is `Nullable<Timestamp>`.
        ///
        /// (Automatically generated by Diesel.)
        tallying_end -> Nullable<Timestamp>,
        /// The `extra` column of the `election` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        extra -> Nullable<Jsonb>,
    }
}

diesel::table! {
    /// Representation of the `goal` table.
    ///
    /// (Automatically generated by Diesel.)
    goal (id) {
        /// The `id` column of the `goal` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `election_id` column of the `goal` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        election_id -> Int4,
        /// The `idx` column of the `goal` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        idx -> Int4,
        /// The `name` column of the `goal` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Varchar,
    }
}

diesel::table! {
    /// Representation of the `proposal` table.
    ///
    /// (Automatically generated by Diesel.)
    proposal (row_id) {
        /// The `row_id` column of the `proposal` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        row_id -> Int4,
        /// The `id` column of the `proposal` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `challenge` column of the `proposal` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        challenge -> Int4,
        /// The `title` column of the `proposal` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        title -> Text,
        /// The `summary` column of the `proposal` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        summary -> Text,
        /// The `public_key` column of the `proposal` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        public_key -> Text,
        /// The `funds` column of the `proposal` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        funds -> Int8,
        /// The `url` column of the `proposal` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        url -> Text,
        /// The `files_url` column of the `proposal` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        files_url -> Text,
        /// The `impact_score` column of the `proposal` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        impact_score -> Int8,
        /// The `extra` column of the `proposal` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        extra -> Nullable<Jsonb>,
        /// The `proposer_name` column of the `proposal` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        proposer_name -> Text,
        /// The `proposer_contact` column of the `proposal` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        proposer_contact -> Text,
        /// The `proposer_url` column of the `proposal` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        proposer_url -> Text,
        /// The `proposer_relevant_experience` column of the `proposal` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        proposer_relevant_experience -> Text,
        /// The `bb_proposal_id` column of the `proposal` table.
        ///
        /// Its SQL type is `Nullable<Bytea>`.
        ///
        /// (Automatically generated by Diesel.)
        bb_proposal_id -> Nullable<Bytea>,
        /// The `bb_vote_options` column of the `proposal` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        bb_vote_options -> Nullable<Text>,
    }
}

diesel::table! {
    /// Representation of the `proposal_voteplan` table.
    ///
    /// (Automatically generated by Diesel.)
    proposal_voteplan (row_id) {
        /// The `row_id` column of the `proposal_voteplan` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        row_id -> Int4,
        /// The `proposal_id` column of the `proposal_voteplan` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        proposal_id -> Nullable<Int4>,
        /// The `voteplan_id` column of the `proposal_voteplan` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        voteplan_id -> Nullable<Int4>,
        /// The `bb_proposal_index` column of the `proposal_voteplan` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        bb_proposal_index -> Nullable<Int8>,
    }
}

diesel::table! {
    /// Representation of the `snapshots` table.
    ///
    /// (Automatically generated by Diesel.)
    snapshots (row_id) {
        /// The `row_id` column of the `snapshots` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        row_id -> Int4,
        /// The `election` column of the `snapshots` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        election -> Int4,
        /// The `as_at` column of the `snapshots` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        as_at -> Timestamp,
        /// The `last_updated` column of the `snapshots` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        last_updated -> Timestamp,
        /// The `final` column of the `snapshots` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        #[sql_name = "final"]
        final_ -> Bool,
        /// The `dbsync_snapshot_cmd` column of the `snapshots` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        dbsync_snapshot_cmd -> Nullable<Text>,
        /// The `dbsync_snapshot_data` column of the `snapshots` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        dbsync_snapshot_data -> Nullable<Text>,
        /// The `drep_data` column of the `snapshots` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        drep_data -> Nullable<Text>,
        /// The `catalyst_snapshot_cmd` column of the `snapshots` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        catalyst_snapshot_cmd -> Nullable<Text>,
        /// The `catalyst_snapshot_data` column of the `snapshots` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        catalyst_snapshot_data -> Nullable<Text>,
    }
}

diesel::table! {
    /// Representation of the `vote_options` table.
    ///
    /// (Automatically generated by Diesel.)
    vote_options (id) {
        /// The `id` column of the `vote_options` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `idea_scale` column of the `vote_options` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        idea_scale -> Nullable<Text>,
        /// The `challenge` column of the `vote_options` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        challenge -> Nullable<Text>,
    }
}

diesel::table! {
    /// Representation of the `voteplan` table.
    ///
    /// (Automatically generated by Diesel.)
    voteplan (row_id) {
        /// The `row_id` column of the `voteplan` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        row_id -> Int4,
        /// The `election_id` column of the `voteplan` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        election_id -> Int4,
        /// The `id` column of the `voteplan` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Varchar,
        /// The `category` column of the `voteplan` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        category -> Text,
        /// The `encryption_key` column of the `voteplan` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        encryption_key -> Nullable<Varchar>,
        /// The `group_id` column of the `voteplan` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        group_id -> Nullable<Int4>,
    }
}

diesel::table! {
    /// Representation of the `voteplan_category` table.
    ///
    /// (Automatically generated by Diesel.)
    voteplan_category (name) {
        /// The `name` column of the `voteplan_category` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `public_key` column of the `voteplan_category` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        public_key -> Nullable<Bool>,
    }
}

diesel::table! {
    /// Representation of the `voters` table.
    ///
    /// (Automatically generated by Diesel.)
    voters (row_id) {
        /// The `row_id` column of the `voters` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        row_id -> Int8,
        /// The `voting_key` column of the `voters` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        voting_key -> Text,
        /// The `snapshot_id` column of the `voters` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        snapshot_id -> Int4,
        /// The `voting_group` column of the `voters` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        voting_group -> Text,
        /// The `voting_power` column of the `voters` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        voting_power -> Int8,
    }
}

diesel::table! {
    /// Representation of the `votes` table.
    ///
    /// (Automatically generated by Diesel.)
    votes (fragment_id) {
        /// The `fragment_id` column of the `votes` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        fragment_id -> Text,
        /// The `caster` column of the `votes` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        caster -> Text,
        /// The `proposal` column of the `votes` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        proposal -> Int4,
        /// The `voteplan_id` column of the `votes` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        voteplan_id -> Text,
        /// The `time` column of the `votes` table.
        ///
        /// Its SQL type is `Float4`.
        ///
        /// (Automatically generated by Diesel.)
        time -> Float4,
        /// The `choice` column of the `votes` table.
        ///
        /// Its SQL type is `Nullable<Int2>`.
        ///
        /// (Automatically generated by Diesel.)
        choice -> Nullable<Int2>,
        /// The `raw_fragment` column of the `votes` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        raw_fragment -> Text,
    }
}

diesel::table! {
    /// Representation of the `voting_group` table.
    ///
    /// (Automatically generated by Diesel.)
    voting_group (row_id) {
        /// The `row_id` column of the `voting_group` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        row_id -> Int4,
        /// The `group_id` column of the `voting_group` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        group_id -> Varchar,
        /// The `election_id` column of the `voting_group` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        election_id -> Int4,
        /// The `token_id` column of the `voting_group` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        token_id -> Nullable<Varchar>,
    }
}

diesel::table! {
    /// Representation of the `voting_nodes` table.
    ///
    /// (Automatically generated by Diesel.)
    voting_nodes (hostname) {
        /// The `hostname` column of the `voting_nodes` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        hostname -> Text,
        /// The `pubkey` column of the `voting_nodes` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        pubkey -> Text,
        /// The `seckey` column of the `voting_nodes` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        seckey -> Text,
        /// The `netkey` column of the `voting_nodes` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        netkey -> Text,
    }
}

diesel::joinable!(challenge -> challenge_category (category));
diesel::joinable!(challenge -> currency (rewards_currency));
diesel::joinable!(challenge -> election (election));
diesel::joinable!(challenge -> vote_options (vote_options));
diesel::joinable!(contributions -> snapshots (snapshot_id));
diesel::joinable!(goal -> election (election_id));
diesel::joinable!(proposal -> challenge (challenge));
diesel::joinable!(proposal_voteplan -> proposal (proposal_id));
diesel::joinable!(proposal_voteplan -> voteplan (voteplan_id));
diesel::joinable!(snapshots -> election (election));
diesel::joinable!(voteplan -> election (election_id));
diesel::joinable!(voteplan -> voteplan_category (category));
diesel::joinable!(voteplan -> voting_group (group_id));
diesel::joinable!(voters -> snapshots (snapshot_id));
diesel::joinable!(voting_group -> election (election_id));

diesel::allow_tables_to_appear_in_same_query!(
    challenge,
    challenge_category,
    community_advisors_review,
    config,
    contributions,
    currency,
    election,
    goal,
    proposal,
    proposal_voteplan,
    snapshots,
    vote_options,
    voteplan,
    voteplan_category,
    voters,
    votes,
    voting_group,
    voting_nodes,
);
