VERSION 0.7
build:
    FROM ../../../+builder
    RUN pwd
    RUN cargo build --locked --release --bin jormungandr

    # Store the artifact
    SAVE ARTIFACT target/release/jormungandr jormungandr
    SAVE IMAGE --cache-hint

docker:
    FROM ../../../+deployment

    WORKDIR /app
    ARG tag="latest"
    ARG registry

    COPY +build/jormungandr .
    COPY entry.sh .
    RUN chmod +x entry.sh

    ENV BIN_PATH=/app/jormungandr
    ENTRYPOINT ["/app/entry.sh"]
    SAVE IMAGE --push ${registry}jormungandr:$tag
