VERSION 0.7

build:
    FROM ../../+builder
    RUN cargo build --locked --release -p vit-servicing-station-cli-f10 -p vit-servicing-station-server-f10

    # Store the artifacts
    SAVE ARTIFACT target/release/vit-servicing-station-cli-f10 vit-servicing-station-cli-f10
    SAVE ARTIFACT target/release/vit-servicing-station-server-f10 vit-servicing-station-server-f10
    SAVE IMAGE --cache-hint