[package]
name = "mjolnir"
version = "0.1.0"
authors = ["dkijania <dariusz.kijania@iohk.io>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jormungandr-lib = { workspace = true }
jortestkit = { path = "../../../jortestkit" }
jormungandr-automation = { path = "../jormungandr-automation" }
rand_core = "0.6"
rand = "0.8"
thiserror = "1.0"
clap = { workspace = true }
assert_fs = "1.0"
indicatif = "0.15"
chain-impl-mockchain = { workspace = true, features = [ "property-test-api" ] }
chain-addr      = { path = "../../../chain-libs/chain-addr", features = [ "property-test-api" ] }
chain-core      = { path = "../../../chain-libs/chain-core" }
chain-crypto    = { path = "../../../chain-libs/chain-crypto", features = [ "property-test-api" ] }
chain-time      = { path = "../../../chain-libs/chain-time" }
chain-storage   = { path = "../../../chain-libs/chain-storage", features = ["with-bench"] }
chain-vote      = { path = "../../../chain-libs/chain-vote" }
tokio = { version = "1.15", features = ["macros"] }
thor = { path = "../thor" }
loki = { path = "../loki" }

[build-dependencies]
versionisator = "1.0.2"
