VERSION 0.7
FROM golang:1.19.6-alpine

deps:
    WORKDIR /work
    COPY go.mod go.sum ./
    RUN go mod download

    # Install external deps
    RUN apk add --no-cache gcc musl-dev

    # Make sure the ginkgo binary is available for the test stage
    RUN go install github.com/onsi/ginkgo/v2

    SAVE ARTIFACT go.mod AS LOCAL go.mod
    SAVE ARTIFACT go.sum AS LOCAL go.sum

check:
    FROM +deps

    COPY --dir cmd pkg pkg .

    RUN go fmt ./...
    RUN go vet ./...

test:
    FROM +check

    RUN ginkgo ./...

build:
    FROM +check

    RUN go build -o bin/ci cmd/main.go

    SAVE ARTIFACT bin/ci ci

docker:
    FROM earthly/earthly:v0.7.4

    ARG tag=latest
    ARG registry

    WORKDIR /workspace

    # Add runtime dependencies
    RUN apk add --no-cache aws-cli git jq

    # Trust WORKDIR
    RUN git config --global --add safe.directory /workspace

    COPY +build/ci /usr/local/bin/ci

    IF [ "$registry" = "" ]
        ARG registry_final=$registry
    ELSE
        ARG registry_final=${registry}/
    END

    ENTRYPOINT ["/usr/local/bin/ci"]
    SAVE IMAGE --push ${registry_final}ci:${tag}