VERSION 0.7

deps:
    FROM python:3.11-slim-bookworm
    WORKDIR /work

    ENV POETRY_HOME=/tmp/poetry
    ENV PATH=$POETRY_HOME/bin:$PATH

    RUN apt-get update && \
        apt-get install -y --no-install-recommends curl

    RUN curl -sSL https://install.python-poetry.org | python3 -

    COPY pyproject.toml .
    COPY poetry.lock .

    RUN poetry install --only main --no-root
    RUN poetry install --only dev --no-root

src:
    FROM +deps

    COPY --dir fragment_exporter tests README.md .

check:
    FROM +src

    RUN poetry run black --check .
    RUN poetry run ruff check .

build:
    FROM +src

    RUN poetry export --without-hashes -f requirements.txt --output requirements.txt
    RUN poetry build --no-cache -f wheel

    SAVE ARTIFACT dist
    SAVE ARTIFACT requirements.txt

test:
    FROM +build

    RUN poetry run pytest -v

publish:
    FROM python:3.11-slim-bookworm
    ARG tag="latest"

    WORKDIR /app

    COPY +build/dist .
    COPY +build/requirements.txt .
    COPY entry.sh /app

    RUN chmod +x entry.sh
    RUN pip3 install --no-cache -r requirements.txt
    RUN pip3 install --no-cache *.whl

    ENTRYPOINT ["/app/entry.sh"]
    SAVE IMAGE fragment-exporter:$tag