version: "3"

services:
  postgres:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: CatalystEventDev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 2s
      timeout: 5s
      retries: 10
    ports:
      - 5432:5432

  migrations:
    image: migrations:latest
    environment:
      # Required environment variables for migrations
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=CatalystEventDev
      - DB_SUPERUSER=postgres
      - DB_SUPERUSER_PASSWORD=postgres
      - DB_USER=catalyst-event-dev
      - DB_USER_PASSWORD=CHANGE_ME
      - ADMIN_ROLE_PASSWORD=CHANGE_ME
      - ADMIN_USER_PASSWORD=CHANGE_ME
      - ANON_ROLE_PASSWORD=CHANGE_ME
      - STAGE=dev
    depends_on:
      postgres:
        condition: service_healthy
