VERSION 0.7

build:
    FROM ../../+builder
    RUN cargo build --locked --release -p iapyx -p valgrind -p vitup

    # Store the artifact
    SAVE ARTIFACT /src/target/release/iapyx iapyx
    SAVE ARTIFACT /src/target/release/iapyx-load iapyx-load
    SAVE ARTIFACT /src/target/release/valgrind valgrind
    SAVE ARTIFACT /src/target/release/vitup vitup
    SAVE IMAGE --cache-hint