# Use docker to build VIT servicing station
[tasks.build-catalyst-core-base]
workspace = false
script_runner = "@shell"
script = '''
docker build --force-rm -t catalyst-core-base:latest -f ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/docker/catalyst-core-base.dockerfile ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}
'''
# Use docker to build jormungandr with jcli
[tasks.build-jormungandr]
workspace = false
script_runner = "@shell"
script = '''
docker build --force-rm -t jormungandr:latest -f ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/docker/jormungandr.dockerfile ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}
'''

# Use docker to build VIT servicing station
[tasks.build-vit]
workspace = false
script_runner = "@shell"
script = '''
docker build --force-rm -t vit-servicing-station:latest -f ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/docker/vit-servicing-station.dockerfile ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}
'''

# Use docker to build the voting node service
[tasks.build-voting-node]
workspace = false
script_runner = "@shell"
script = '''
docker build --force-rm -t voting-node:latest -f ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/docker/voting-node.dockerfile ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/services/voting-node
'''

[tasks.build-all]
workspace = false
dependencies = [
    "build-catalyst-core-base",
    "build-jormungandr",
    "build-vit",
    "build-voting-node"
]

# Use docker-compose to build and run deployment
[tasks.voting-deploy-up]
workspace = false
script_runner = "@shell"
script = '''
docker-compose -f ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/services/voting-node/docker-compose.yml up
'''

# Use docker-compose to remove deployment artifacts
[tasks.voting-deploy-down]
workspace = false
script_runner = "@shell"
script = '''
docker-compose -f ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/services/voting-node/docker-compose.yml down -v --remove-orphans --rmi local
'''
