[tasks.build-catalyst-core-base]
workspace = false
category = "Voting"
description = "Builds docker image with Rust tooling and catalyst-core monorepo which can be used for multi-stage dockerfiles to package individual crates."
script_runner = "@shell"
script = '''
docker build --force-rm -t catalyst-core-base:latest -f ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/docker/catalyst-core-base.dockerfile ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}
'''
[tasks.build-jormungandr]
workspace = false
category = "Voting"
description = "Builds docker image with jormungandr and jcli."
script_runner = "@shell"
script = '''
docker build --force-rm -t jormungandr:latest -f ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/docker/jormungandr.dockerfile ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}
'''

[tasks.build-eventdb]
workspace = false
category = "Voting"
description = "Builds docker image with PostgreSQL setup with EventDB configuration."
script_runner = "@shell"
script = '''
docker build --force-rm -t eventdb:latest -f ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/docker/eventdb-postgres.dockerfile ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}
'''

[tasks.build-eventdb-graphql]
workspace = false
category = "Voting"
description = "Builds docker image with PostGraphile for EventDB."
script_runner = "@shell"
script = '''
docker build --force-rm -t eventdb-graphql:latest -f ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/docker/eventdb-graphql.dockerfile ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}
'''

[tasks.build-cat-data-service]
workspace = false
category = "Voting"
description = "Builds docker image with cat-data-service."
script_runner = "@shell"
script = '''
docker build --force-rm -t cat-data-service:latest -f ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/docker/cat-data-service.dockerfile ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}
'''

[tasks.build-catalyst-toolbox]
workspace = false
category = "Voting"
description = "Builds docker image with catalyst-toolbox."
script_runner = "@shell"
script = '''
docker build --force-rm -t catalyst-toolbox:latest -f ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/docker/catalyst-toolbox.dockerfile ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}
'''

[tasks.build-snapshot-tool]
workspace = false
category = "Voting"
description = "Builds docker image with snapshot-tool."
script_runner = "@shell"
script = '''
docker build --force-rm -t snapshot-tool:latest -f ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/docker/snapshot-tool.dockerfile ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/services/voting-node
'''

[tasks.build-voting-node]
workspace = false
category = "Voting"
description = "Builds docker image with voting-node."
script_runner = "@shell"
script = '''
docker build --force-rm -t voting-node:latest -f ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/docker/voting-node.dockerfile ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/services/voting-node
'''

[tasks.build-all]
workspace = false
category = "Voting"
description = "Builds all docker images used in Voting."
dependencies = [
    "build-catalyst-core-base",
    "build-jormungandr",
    "build-vit",
    "build-voting-node"
]

[tasks.voting-deploy-up]
workspace = false
category = "Voting"
description = "Deploys the docker-compose services for voting."
script_runner = "@shell"
script = '''
docker-compose -f ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/services/voting-node/docker-compose.yml up
'''

[tasks.voting-deploy-down]
workspace = false
category = "Voting"
description = "Use docker-compose to remove deployment artifacts."
script_runner = "@shell"
script = '''
docker-compose -f ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/services/voting-node/docker-compose.yml down -v --remove-orphans --rmi local
'''
