[package]
name = "jcli"
version = "0.13.0"
authors = [ "dev@iohk.io" ]
license = "MIT OR Apache-2.0"
repository = "https://github.com/input-output-hk/jormungandr"
homepage = "https://github.com/input-output-hk/jormungandr#README.md"
documentation = "https://github.com/input-output-hk/jormungandr#USAGE.md"
description = """
Midgard Serpent
"""
edition = "2021"

[dependencies]
clap = { workspace = true }
clap_complete = { workspace = true }
rand = "0.8"
rand_chacha = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0.81"
serde_yaml = "0.8"
bincode = "1.3.3"
bech32 = "0.8"
hex = "0.4.2"
rayon = "1.5"
base64 = "0.13.0"
chain-core      = { path = "../../chain-libs/chain-core" }
chain-impl-mockchain = { workspace = true }
chain-addr      = { path = "../../chain-libs/chain-addr" }
chain-crypto    = { path = "../../chain-libs/chain-crypto" }
chain-time    = { path = "../../chain-libs/chain-time" }
chain-vote = { path = "../../chain-libs/chain-vote" }
jormungandr-lib = { workspace = true }
gtmpl = "0.6.0"
ed25519-bip32 = "0.4.1"
thiserror = "1.0"
bytes = "1.1"
rpassword = "6.0"
reqwest = { workspace = true }

[dev-dependencies]
assert_fs = "1.0"
predicates = "2.0"
quickcheck = "0.9"
# FIXME required to work with quickcheck 0.9. Remove after migrating another crate or newer quickcheck
rand07 = { package = "rand", version = "0.7" }
chain-impl-mockchain = { workspace = true, features = [ "property-test-api" ] }

[build-dependencies]
versionisator = "1.0.2"

[lib]
name = "jcli_lib"
path = "src/lib.rs"

[[bin]]
name = "jcli"
path = "src/main.rs"
