VERSION 0.7

build:
    FROM ../../../+build-workspace
    RUN with_nix cargo build --locked --release --bin jcli
    # Store the artifact in a temporary directory, so that it can be used as a dependency
    SAVE ARTIFACT target/release/jcli jcli

docker:
    FROM debian:bullseye-slim

    WORKDIR /app
    ARG tag="latest"
    ARG registry

    COPY +build/jcli .
    ENTRYPOINT ["/app/jcli"]
    SAVE IMAGE ${registry}jcli:$tag
