VERSION 0.7
FROM debian:bullseye-slim

WORKDIR /app

build:
    FROM ../../../+build-workspace
    RUN cargo build --locked --release --bin jcli
    # Store the artifact in a temporary directory, so that it can be used as a dependency
    SAVE ARTIFACT target/release/jcli jcli

docker:
    COPY +build/jcli .
    ENTRYPOINT ["/app/jcli"]
    SAVE IMAGE jcli:latest
