name: CIv2

on:
  push:
    # branches:
    #   - main

permissions:
  id-token: write
  contents: read
  packages: write

env:
  AWS_REGION: eu-central-1
  AWS_ROLE_ARN: arn:aws:iam::332405224602:role/ci
  ECR_REGISTRY: 332405224602.dkr.ecr.eu-central-1.amazonaws.com

jobs:

  discover:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/input-output-hk/catalyst-core/ci:latest
    defaults:
      run:
        shell: bash
        working-directory: /workspace
    outputs:
      deployment: ${{ steps.discover.outputs.images }}
      earthly: ${{ steps.discover.outputs.json }}
      tag: ${{ steps.discover.outputs.tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/setup-workspace
      - name: Discover Earthfiles
        id: discover
        run: |
          TAG="${{ github.sha }}"
          #JSON_OUTPUT=$(ci scan -jit docker ./containers ./src ./services ./utilities)
          JSON_OUTPUT=$(ci scan -jit docker ./containers)

          DEPLOYMENT=$(echo "$JSON_OUTPUT" | jq -cr --arg tag "${TAG}" '[.[] .images[] | { (.): $tag }] | add')
          EARTHLY=$(echo "$JSON_OUTPUT" | jq -cr '[.[] | .images |= join(" ")]')

          echo "deployment=$DEPLOYMENT" >>$GITHUB_OUTPUT
          echo "earthly=$EARTHLY" >>$GITHUB_OUTPUT
          echo "tag=$TAG" >>$GITHUB_OUTPUT

  cache:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/input-output-hk/catalyst-core/ci:latest
    defaults:
      run:
        shell: bash
        working-directory: /workspace

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/setup-workspace
      - uses: ./.github/actions/setup-earthly
        with:
          aws_role_arn: ${{ env.AWS_ROLE_ARN }}
          aws_region: ${{ env.AWS_REGION }}
      - name: Build cache
        run: |
          earthly \
          --buildkit-host "tcp://${{ secrets.EARTHLY_SATELLITE_ADDRESS }}:8372" \
          "$(pwd)+builder"

  build:
    needs: [cache, discover]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/input-output-hk/catalyst-core/ci:latest
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      env:
        FORCE_COLOR: 1
    defaults:
      run:
        shell: bash
        working-directory: /workspace
    strategy:
      matrix:
        target: ${{ fromJson(needs.discover.outputs.earthly) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/setup-workspace
      - uses: ./.github/actions/setup-earthly
        with:
          aws_role_arn: ${{ env.AWS_ROLE_ARN }}
          aws_region: ${{ env.AWS_REGION }}
      - name: Login to ECR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.ECR_REGISTRY }}
      - name: Build ${{ matrix.target.path }}+docker
        run: |
          earthly \
            --buildkit-host "tcp://${{ secrets.EARTHLY_SATELLITE_ADDRESS }}:8372" \
            ${{ matrix.target.path }}+docker \
            --tag=latest

          TAG=${{ needs.discover.outputs.tag }}
          for image in ${{ matrix.target.images }}; do
            echo "Tagging ${image}:latest as ${{ env.ECR_REGISTRY }}/${image}:${TAG}"
            docker tag "${image}:latest" "${{ env.ECR_REGISTRY }}/${image}:${TAG}"

            echo "Pushing ${{ env.ECR_REGISTRY }}/${image}:${TAG}"
            docker push "${{ env.ECR_REGISTRY }}/${image}:${TAG}"
          done

  deploy:
    needs: [build, discover]
    runs-on: ubuntu-latest
    steps:
      - name: Print deployment payload
        run: |
          echo "${{ needs.discover.outputs.deployment }}" | jq