name: CIv2

on:
  push:
    # branches:
    #   - main

permissions:
  id-token: write
  contents: read
  packages: write

env:
  AWS_REGION: eu-central-1
  AWS_ROLE_ARN: arn:aws:iam::332405224602:role/ci
  ECR_REGISTRY: 332405224602.dkr.ecr.eu-central-1.amazonaws.com

jobs:
  discover:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      - name: Install Earthly
        uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.7.0
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Put back the git branch into git (Earthly uses it for tagging)
        run: |
          branch=""
          if [ -n "$GITHUB_HEAD_REF" ]; then
            branch="$GITHUB_HEAD_REF"
          else
            branch="${GITHUB_REF##*/}"
          fi
          git checkout -b "$branch" || true
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Login to ECR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.ECR_REGISTRY }}
      - name: Configure Earthly remote runner
        run: |
            mkdir -p /tmp/certs

            JSON=$(aws secretsmanager get-secret-value --secret-id global/ci/ci-tls --query SecretString --output text)
            echo "${JSON}" | jq -r .private_key | sed 's/\\n/\n/g' > /tmp/certs/key.pem
            echo "${JSON}" | jq -r .certificate | sed 's/\\n/\n/g' > /tmp/certs/cert.pem
            echo "${JSON}" | jq -r .ca_certificate | sed 's/\\n/\n/g' > /tmp/certs/ca.pem

            earthly config global.tlskey /tmp/certs/key.pem
            earthly config global.tlscert /tmp/certs/cert.pem
            earthly config global.tlsca /tmp/certs/ca.pem
      - name: Discover Earthfiles
        id: discover
        run: |
          JSON_OUTPUT=$(docker run -v $(pwd):/workspace ghcr.io/input-output-hk/catalyst-core/ci:latest scan -jt +docker ./containers ./src ./services)
          echo "$JSON_OUTPUT"
          echo "json=$JSON_OUTPUT" >>$GITHUB_OUTPUT

  build:
    needs: discover
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     path: ${{fromJson(needs.discover.outputs.json)}}
    steps:
      - name: Print JSON
        run: |
          echo "JSON: ${{ needs.discover.outputs.json }}"