name: "PR Title is Conventional and has a Jira Issue ID"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  contents: read

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      statuses: write
    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^(?:feat|fix|docs|style|refactor|test|chore|build|ci|perf|revert)(?:\(.+\))?:\s.+(\s\|\s)(NPG-\d+)$'
          github_token: ${{ github.token }}
